'use client'

import { Badge } from '@repo/ui/badge'
import { DataTable } from '@repo/ui/data-table'
import { ColumnDef } from '@tanstack/table-core'
import { GlobeIcon, LockIcon, StarsIcon } from 'lucide-react'
import React from 'react'
import { Group, GroupOrder, User } from '@repo/codegen/src/schema'
import AvatarList from '@/components/shared/avatar-list/avatar-list'
import { useGroupsStore } from '@/hooks/useGroupsStore'
import { GROUP_SORT_FIELDS } from '@/components/pages/protected/groups/table/table-config.ts'
import { TPagination } from '@repo/ui/pagination-types'
import { useGetAllGroups } from '@/lib/graphql-hooks/groups.ts'

const columns: ColumnDef<Group>[] = [
  {
    header: 'Name',
    accessorKey: 'name',
    cell: ({ row }) => {
      const isAutoGenerated = row.original.isManaged

      return (
        <div className="flex gap-2">
          {isAutoGenerated ? (
            <div className="flex gap-1 ">
              <StarsIcon className="mt-0.5" width={16} height={16} />
              <div className="flex flex-col gap-1 ">
                <span className="text-sm whitespace-nowrap">{row.getValue('name')}</span>
                <p className="text-xs text-text-light">Prebuilt</p>
              </div>
            </div>
          ) : (
            <span>{row.getValue('name')}</span>
          )}
        </div>
      )
    },
  },
  {
    header: 'Description',
    accessorKey: 'description',
    cell: ({ row }) => (
      <div>
        <p>{row.getValue('description')}</p>
        {!!row.original?.tags?.length && (
          <div className="mt-2 border-t border-dashed pt-2 flex flex-wrap gap-2">
            {row.original.tags.map((tag: string, index: number) => (
              <Badge key={index} variant="outline">
                {tag}
              </Badge>
            ))}
          </div>
        )}
      </div>
    ),
  },
  {
    header: 'Visibility',
    accessorKey: 'visibility',
    cell: ({ row }) => {
      const value = row.original.setting?.visibility!
      return (
        <span className="flex items-center gap-2 capitalize">
          {value === 'PUBLIC' ? <GlobeIcon height={18} /> : <LockIcon height={18} />}
          {value.toLowerCase()}
        </span>
      )
    },
  },
  {
    header: 'Members',
    accessorKey: 'members',
    cell: ({ row }) => {
      const members = row.original.members.edges?.map((user) => user?.node?.user as User) || []

      return (
        <div className="flex items-center gap-2">
          {members && members.length > 0 ? (
            <AvatarList
              max={10}
              data={members.map((user) => ({
                id: user.id,
                imageUrl: user.avatarFile?.presignedURL ?? user.avatarRemoteURL ?? undefined,
                fallback: user.displayName?.substring(0, 2) ?? undefined,
                displayName: user?.displayName ?? undefined,
              }))}
            />
          ) : (
            <span className="text-gray-500">No members</span>
          )}
        </div>
      )
    },
  },
]

type TGroupsTableProps = {
  onSortChange?: (sortCondition: any[]) => void
  pagination: TPagination
  onPaginationChange: (pagination: TPagination) => void
  whereFilter: Record<string, any> | null
  orderByFilter: GroupOrder[] | GroupOrder | undefined
}

const GroupsTable = ({ onSortChange, pagination, onPaginationChange, whereFilter, orderByFilter }: TGroupsTableProps) => {
  const { groups, isError, paginationMeta } = useGetAllGroups({
    where: whereFilter,
    orderBy: orderByFilter,
    pagination: pagination,
    enabled: !!whereFilter,
  })
  const { setSelectedGroup } = useGroupsStore()

  const handleRowClick = (group: Group) => {
    setSelectedGroup(group.id)
  }

  if (isError) {
    return <p className="text-red-500">Error loading groups</p>
  }

  return (
    <div className="mt-5">
      <DataTable
        columns={columns as ColumnDef<Group>[]}
        data={groups}
        onRowClick={handleRowClick}
        sortFields={GROUP_SORT_FIELDS}
        onSortChange={onSortChange}
        pagination={pagination}
        onPaginationChange={(pagination: TPagination) => onPaginationChange(pagination)}
        paginationMeta={paginationMeta}
      />
    </div>
  )
}

export default GroupsTable
