import { useQuery } from '@tanstack/react-query'
import { useGraphQLClient } from '@/hooks/useGraphQLClient'
import { GET_ALL_NARRATIVES } from '@repo/codegen/query/narrative'

// Types generated by your code generator
import { GetAllNarrativesQuery, GetAllNarrativesQueryVariables } from '@repo/codegen/src/schema'

/**
 * A hook to fetch all Narratives, optionally filtered by a `where` clause.
 */
export const useGetAllNarratives = (where?: GetAllNarrativesQueryVariables['where']) => {
  const { client } = useGraphQLClient()

  return useQuery<GetAllNarrativesQuery>({
    queryKey: ['narratives', where],
    queryFn: () => client.request(GET_ALL_NARRATIVES, { where }),
    enabled: true, // or conditionally enable if needed
  })
}
