'use client'
import React, { useMemo, useState, useEffect } from 'react'
import { PageHeading } from '@repo/ui/page-heading'
import GroupsTable from '@/components/pages/protected/groups/components/groups-table'
import { CirclePlus, CreditCard as CardIcon, SearchIcon, Table as TableIcon } from 'lucide-react'
import { Checkbox } from '@repo/ui/checkbox'
import { GetAllGroupsQueryVariables, GroupSettingVisibility, GroupWhereInput } from '@repo/codegen/src/schema'
import CreateGroupDialog from './components/dialogs/create-group-dialog'
import GroupDetailsSheet from './components/group-details-sheet'
import { Input } from '@repo/ui/input'
import { TableFilter } from '@/components/shared/table-filter/table-filter'
import { FilterField, SelectFilterField } from '@/types'
import { useSession } from 'next-auth/react'
import { useDebounce } from '@uidotdev/usehooks'
import { TPagination } from '@repo/ui/pagination-types'
import { DEFAULT_PAGINATION } from '@/constants/pagination'
import GroupInfiniteCards from '@/components/pages/protected/groups/components/group-infinite-cards.tsx'
import Menu from '@/components/shared/menu/menu.tsx'
import { CreateBtn } from '@/components/shared/enum-mapper/common-enum'
import { VisibilityState } from '@tanstack/react-table'
import { getGroupTableColumns } from './table/columns'
import ColumnVisibilityMenu from '@/components/shared/column-visibility-menu/column-visibility-menu'
import { BreadcrumbContext } from '@/providers/BreadcrumbContext'

const filterFields: FilterField[] = [
  { key: 'name', label: 'Name', type: 'text' },
  {
    key: 'visibility',
    label: 'Visibility',
    type: 'select',
    options: [
      { label: 'Public', value: GroupSettingVisibility.PUBLIC },
      { label: 'Private', value: GroupSettingVisibility.PRIVATE },
    ],
  } as SelectFilterField,
]

const GroupsPage = () => {
  const [activeTab, setActiveTab] = useState<'table' | 'card'>('table')
  const [whereFilters, setWhereFilters] = useState<GroupWhereInput | null>(null)
  const [orderBy, setOrderBy] = useState<GetAllGroupsQueryVariables['orderBy']>()
  const [searchQuery, setSearchQuery] = useState('')
  const { data: session } = useSession()
  const debouncedSearchQuery = useDebounce(searchQuery, 300)
  const [showAutoGenerated, setShowAutoGenerated] = useState<boolean>(true)
  const [pagination, setPagination] = useState<TPagination>(DEFAULT_PAGINATION)
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({ updatedAt: false, updatedBy: false, createdAt: false, createdBy: false })
  const IsMyGroups = false
  const { setCrumbs } = React.useContext(BreadcrumbContext)

  useEffect(() => {
    setCrumbs([
      { label: 'Home', href: '/dashboard' },
      { label: 'Groups', href: '/groups' },
    ])
  }, [setCrumbs])

  const whereFilter = useMemo(() => {
    if (!whereFilters) {
      return null
    }
    const modifiedWhereFilters = { ...whereFilters }

    if ('visibility' in modifiedWhereFilters) {
      modifiedWhereFilters.hasSettingWith = [{ visibility: modifiedWhereFilters.visibility as GroupSettingVisibility }]
      delete modifiedWhereFilters.visibility
    }

    const conditions: GroupWhereInput = {
      ...(IsMyGroups && session ? { hasMembersWith: [{ userID: session.user?.userId || '' }] } : {}),
      ...(!showAutoGenerated ? { isManaged: false } : {}),
      ...modifiedWhereFilters,
      nameContainsFold: debouncedSearchQuery,
    }

    return conditions
  }, [IsMyGroups, session, showAutoGenerated, debouncedSearchQuery, whereFilters])

  const orderByFilter = useMemo(() => {
    return orderBy || undefined
  }, [orderBy])

  const { mappedColumns } = getGroupTableColumns({})

  return (
    <>
      <PageHeading heading={'Groups'} />
      <div className="flex items-center gap-2 my-2">
        <div className="flex gap-1 size-fit bg-transparent py-0.5 px-1 border rounded-md">
          <div className={`py-1.5 px-2.5 rounded-md cursor-pointer ${activeTab === 'table' ? 'bg-card' : 'bg-transparent'}`} onClick={() => setActiveTab('table')}>
            <TableIcon size={16} />
          </div>
          <div className={`py-1.5 px-2.5 rounded-md cursor-pointer ${activeTab === 'card' ? 'bg-card' : 'bg-transparent'}`} onClick={() => setActiveTab('card')}>
            <CardIcon size={16} />
          </div>
        </div>
        {mappedColumns && columnVisibility && setColumnVisibility && (
          <ColumnVisibilityMenu mappedColumns={mappedColumns} columnVisibility={columnVisibility} setColumnVisibility={setColumnVisibility}></ColumnVisibilityMenu>
        )}
        <TableFilter filterFields={filterFields} onFilterChange={setWhereFilters} />
        <Input
          value={searchQuery}
          name="groupSearch"
          placeholder="Search..."
          onChange={(e) => setSearchQuery(e.currentTarget.value)}
          icon={<SearchIcon width={17} />}
          iconPosition="left"
          variant="searchTable"
        />
        <div className="flex gap-2">
          <Checkbox checked={showAutoGenerated} onCheckedChange={(val: boolean) => setShowAutoGenerated(val)} />
          <p>Show auto generated group</p>
        </div>
        <div className="grow flex flex-row items-center gap-2 justify-end">
          <Menu
            trigger={CreateBtn}
            content={
              <CreateGroupDialog
                trigger={
                  <div className="flex items-center space-x-2">
                    <CirclePlus size={16} strokeWidth={2} />
                    <span>Group</span>
                  </div>
                }
              />
            }
          />
        </div>
      </div>
      <div id="datatable-filter-portal" />

      {activeTab === 'table' ? (
        <GroupsTable
          key="table"
          onSortChange={setOrderBy}
          whereFilter={whereFilter}
          orderByFilter={orderByFilter}
          pagination={pagination}
          onPaginationChange={(pagination: TPagination) => setPagination(pagination)}
          columnVisibility={columnVisibility}
          setColumnVisibility={setColumnVisibility}
        />
      ) : (
        <GroupInfiniteCards whereFilter={whereFilter} orderByFilter={orderByFilter} />
      )}

      <GroupDetailsSheet />
    </>
  )
}

export default GroupsPage
