version: '3'

env:
  ENV: config

dotenv: ['.env', '{{.ENV}}/.env']

includes:
  codegen:
    taskfile: ./packages/codegen/Taskfile.yaml
    dir: ./packages/codegen

tasks:
  default:
    silent: true
    cmds:
      - task --list

  local-setup:
    desc: Setup the project dependencies
    cmds:
      - task: install-bun
      - task: install-precommit
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files

  install-bun:
    desc: install bun package manager
    cmd: curl -fsSL https://bun.sh/install | bash

  install-precommit:
    desc: install pre-commit
    cmd: brew install pre-commit

  build:
    desc: build all apps and package
    cmd: bun run build

  build:dev:
    dir: apps/console
    desc: build console in dev mode with debug info
    cmd: bun run debug

  install:
    desc: install the dependencies listed in package.json
    cmds:
      - bun install

  reinstall:
    desc: reinstall the dependencies listed in package.json
    cmds:
      - task: clean
      - bun install --dev turbo@latest
      - bun run turbo-clean
      - task: install

  test:
    desc: run all tests
    cmds:
      - bun test

  clean:
    desc: clean all apps and package
    cmd: bun run clean

  dev:
    desc: develop all apps
    cmds:
      - task: install
      - bun dev

  dev:console:
    desc: develop console
    cmds:
      - task: install
      - bun dev --filter={apps/console}

  dev:storybook:
    desc: develop storybook
    cmds:
      - task: install
      - bun dev --filter={apps/storybook}

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files

  update:passkeys:
    desc: Update the known passkey aaguids. This should be run periodically
    cmds:
      - curl https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/refs/heads/main/aaguid.json -o apps/console/src/lib/passkeys.json

  generate:routes:
    desc: Generate static route list from app folders
    cmds:
      - bun tsc --project apps/console/scripts/tsconfig.routes.json
      - bun run apps/console/scripts/generateRoutes.js

  update:routes:
    desc: Generate static route list from app folders
    cmds:
      - bun tsc --project apps/console/scripts/tsconfig.routes.json
      - bun run apps/console/scripts/updateRoutes.js
