import { ITheme } from "survey-core";

export const lightTheme : ITheme = {
    "backgroundImageFit": "cover",
    "backgroundImageAttachment": "scroll",
    "backgroundOpacity": 1,
    "cssVariables": {
            "--sjs-corner-radius": "4px",
            "--sjs-base-unit": "8px",
            "--sjs-font-pagetitle-color": "#082930",
            "--sjs-font-pagedescription-color":  "#082930",
            "--sjs-font-surveytitle-color": "#082930",
            "--sjs-shadow-small": "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-inner": "inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-default": "#c2d7df",
            "--sjs-border-light": "#c2d7df",
            "--background": "#ffffff",
            "--background-dim": "#ffffff",
            "--ctr-menu-item-border-color-selected": "#09f1c7",
            "--sjs-general-backcolor": "#e9f1f5",
            "--sjs-general-backcolor-dark": "#303e4a",
            "--sjs-general-backcolor-dim-light": "#e9f1f5",
            "--sjs-general-backcolor-dim-dark": "#303e4a",
            "--sjs-question-background": "#ffffff",
            "--sjs-editor-background": "#ffffff",
            "--ctr-property-grid-form-background-color": "#e9f1f5",
            "--sjs-general-forecolor": "#082930",
            "--sjs-general-forecolor-light": "#082930",
            "--sjs-general-dim-forecolor": "#082930",
            "--sjs-general-dim-forecolor-light": "#082930",
            "--ctr-survey-page-header-title-color-placeholder": "#082930",
            "--foreground": "#082930",
            "--ctr-property-grid-search-text-color": "#082930",
            "--sjs-secondary-backcolor": "#09f1c7",
            "--sjs-secondary-backcolor-light": "#09f1c7",
            "--sjs-secondary-backcolor-semi-light": "#09f1c7",
            "--sjs-secondary-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-secondary-forecolor-light": "rgba(255, 255, 255, 0.25)",
            "--sjs-shadow-small-reset": "0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-medium": "0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-inner-reset": "inset 0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-inside": "#c2d7df",
            "--sjs-special-red-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-green": "rgba(25, 179, 148, 1)",
            "--sjs-special-green-light": "rgba(25, 179, 148, 0.1)",
            "--sjs-special-green-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-blue": "rgba(67, 127, 217, 1)",
            "--sjs-special-blue-light": "rgba(67, 127, 217, 0.1)",
            "--sjs-special-blue-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
            "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
            "--sjs-special-yellow-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-article-font-xx-large-textDecoration": "none",
            "--sjs-article-font-xx-large-fontWeight": "400",
            "--sjs-article-font-xx-large-fontStyle": "normal",
            "--sjs-article-font-xx-large-fontStretch": "normal",
            "--sjs-article-font-xx-large-letterSpacing": "0",
            "--sjs-article-font-xx-large-lineHeight": "64px",
            "--sjs-article-font-xx-large-paragraphIndent": "0px",
            "--sjs-article-font-xx-large-textCase": "none",
            "--sjs-article-font-x-large-textDecoration": "none",
            "--sjs-article-font-x-large-fontWeight": "400",
            "--sjs-article-font-x-large-fontStyle": "normal",
            "--sjs-article-font-x-large-fontStretch": "normal",
            "--sjs-article-font-x-large-letterSpacing": "0",
            "--sjs-article-font-x-large-lineHeight": "56px",
            "--sjs-article-font-x-large-paragraphIndent": "0px",
            "--sjs-article-font-x-large-textCase": "none",
            "--sjs-article-font-large-textDecoration": "none",
            "--sjs-article-font-large-fontWeight": "400",
            "--sjs-article-font-large-fontStyle": "normal",
            "--sjs-article-font-large-fontStretch": "normal",
            "--sjs-article-font-large-letterSpacing": "0",
            "--sjs-article-font-large-lineHeight": "40px",
            "--sjs-article-font-large-paragraphIndent": "0px",
            "--sjs-article-font-large-textCase": "none",
            "--sjs-article-font-medium-textDecoration": "none",
            "--sjs-article-font-medium-fontWeight": "400",
            "--sjs-article-font-medium-fontStyle": "normal",
            "--sjs-article-font-medium-fontStretch": "normal",
            "--sjs-article-font-medium-letterSpacing": "0",
            "--sjs-article-font-medium-lineHeight": "32px",
            "--sjs-article-font-medium-paragraphIndent": "0px",
            "--sjs-article-font-medium-textCase": "none",
            "--sjs-article-font-default-textDecoration": "none",
            "--sjs-article-font-default-fontWeight": "400",
            "--sjs-article-font-default-fontStyle": "normal",
            "--sjs-article-font-default-fontStretch": "normal",
            "--sjs-article-font-default-letterSpacing": "0",
            "--sjs-article-font-default-lineHeight": "28px",
            "--sjs-article-font-default-paragraphIndent": "0px",
            "--sjs-article-font-default-textCase": "none",
            "--sjs-general-backcolor-dim": "#e9f1f5",
            "--sjs-primary-backcolor": "#09f1c7",
            "--sjs-primary-backcolor-dark": "#09f1c7",
            "--sjs-secondary-background-800": "#007364",
            "--sjs-secondary-background-700": "#00927d",
            "--sjs-secondary-background-600": "#00b696",
            "--sjs-secondary-background-500": "#00deb7",
            "--sjs-secondary-background-400": "#09f1c7",
            "--sjs-secondary-background-300": "#53ffdd",
            "--sjs-secondary-background-200": "#96ffe4",
            "--sjs-secondary-background-100": "#c8ffef",
            "--sjs-secondary-background-10": "#c8ffef",
            "--sjs-secondary-background-25": "#c8ffef",
            "--sjs-secondary-background-50": "#c8ffef",
            "--sjs-primary-backcolor-light": "#09f1c7",
            "--sjs-primary-background-500": "#09f1c7",
            "--sjs-primary-forecolor": "#082930",
            "--sjs-primary-forecolor-light": "#082930",
            "--sjs-special-red": "rgba(229, 10, 62, 1)",
            "--sjs-special-red-light": "rgba(229, 10, 62, 0.1)",
            "--sjs-font-surveytitle-family": "var(--font-mincho)",
            "--sjs-font-headertitle-family": "var(--font-mincho)",
            "--ctr-font-family-code": "var(--font-outfit)",
            "--sjs-default-font-family": "var(--font-outfit)",
            "--sjs-font-family": "var(--font-outfit)",
            "--sjs-font-headertitle-weight": "400",
            "--sjs-header-backcolor": "#09f1c7",
            "--ctr-survey-question-panel-toolbar-item-icon-color": "#09f1c7",
        },
        "themeName": "openlane",
        "colorPalette": "light",
        "isPanelless": true,
}

export const darkTheme : ITheme = {
    "backgroundImageFit": "cover",
    "backgroundImageAttachment": "scroll",
    "backgroundOpacity": 1,
    "cssVariables": {
            "--ctr-page-banner-text-color": "#082930",
            "--ctr-button-text-color": "#bdd9e1",
            "--ctr-button-background-color": "#2a4750",
            "--ctr-surface-placeholder-text-title-color": "#bdd9e1",
            "--ctr-surface-placeholder-text-description-color": "#bdd9e1",
            "--foreground-light": "#bdd9e1",
            "--sjs-corner-radius": "4px",
            "--sjs-base-unit": "8px",
            "--sjs-font-pagetitle-color": "#bdd9e1",
            "--sjs-font-pagedescription-color": "#bdd9e1",
            "--sjs-font-surveytitle-color": "#bdd9e1",
            "--sjs-shadow-small": "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-inner": "inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-default":"#c2d7df",
            "--sjs-border-light": "#c2d7df",
            "--ctr-menu-item-border-color-selected": "#09f1c7",
            "--background": "#2a4750",
            "--background-dim": "#2a4750",
            "--sjs-general-backcolor": "#303e4a",
            "--sjs-general-backcolor-dark": "#303e4a",
            "--sjs-general-backcolor-dim-light": "#e9f1f5",
            "--sjs-general-backcolor-dim-dark": "#303e4a",
            "--sjs-question-background": "#2a4750",
            "--sjs-editor-background": "#303e4a",
            "--ctr-property-grid-form-background-color": "#303e4a",
            "--sjs-general-forecolor": "#bdd9e1",
            "--sjs-general-forecolor-light":  "#bdd9e1",
            "--sjs-general-dim-forecolor":  "#bdd9e1",
            "--sjs-general-dim-forecolor-light":  "#bdd9e1",
            "--ctr-survey-page-header-title-color-placeholder": "#bdd9e1",
            "--foreground": "#bdd9e1",
            "--ctr-property-grid-search-text-color": "#bdd9e1",
            "--sjs-secondary-backcolor": "#09f1c7",
            "--sjs-secondary-backcolor-light": "#09f1c7",
            "--sjs-secondary-backcolor-semi-light": "#09f1c7",
            "--sjs-secondary-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-secondary-forecolor-light": "rgba(255, 255, 255, 0.25)",
            "--sjs-shadow-small-reset": "0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-medium": "0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-inner-reset": "inset 0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-inside": "#c2d7df",
            "--sjs-special-red-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-green": "rgba(25, 179, 148, 1)",
            "--sjs-special-green-light": "rgba(25, 179, 148, 0.1)",
            "--sjs-special-green-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-blue": "rgba(67, 127, 217, 1)",
            "--sjs-special-blue-light": "rgba(67, 127, 217, 0.1)",
            "--sjs-special-blue-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
            "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
            "--sjs-special-yellow-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-article-font-xx-large-textDecoration": "none",
            "--sjs-article-font-xx-large-fontWeight": "400",
            "--sjs-article-font-xx-large-fontStyle": "normal",
            "--sjs-article-font-xx-large-fontStretch": "normal",
            "--sjs-article-font-xx-large-letterSpacing": "0",
            "--sjs-article-font-xx-large-lineHeight": "64px",
            "--sjs-article-font-xx-large-paragraphIndent": "0px",
            "--sjs-article-font-xx-large-textCase": "none",
            "--sjs-article-font-x-large-textDecoration": "none",
            "--sjs-article-font-x-large-fontWeight": "400",
            "--sjs-article-font-x-large-fontStyle": "normal",
            "--sjs-article-font-x-large-fontStretch": "normal",
            "--sjs-article-font-x-large-letterSpacing": "0",
            "--sjs-article-font-x-large-lineHeight": "56px",
            "--sjs-article-font-x-large-paragraphIndent": "0px",
            "--sjs-article-font-x-large-textCase": "none",
            "--sjs-article-font-large-textDecoration": "none",
            "--sjs-article-font-large-fontWeight": "400",
            "--sjs-article-font-large-fontStyle": "normal",
            "--sjs-article-font-large-fontStretch": "normal",
            "--sjs-article-font-large-letterSpacing": "0",
            "--sjs-article-font-large-lineHeight": "40px",
            "--sjs-article-font-large-paragraphIndent": "0px",
            "--sjs-article-font-large-textCase": "none",
            "--sjs-article-font-medium-textDecoration": "none",
            "--sjs-article-font-medium-fontWeight": "400",
            "--sjs-article-font-medium-fontStyle": "normal",
            "--sjs-article-font-medium-fontStretch": "normal",
            "--sjs-article-font-medium-letterSpacing": "0",
            "--sjs-article-font-medium-lineHeight": "32px",
            "--sjs-article-font-medium-paragraphIndent": "0px",
            "--sjs-article-font-medium-textCase": "none",
            "--sjs-article-font-default-textDecoration": "none",
            "--sjs-article-font-default-fontWeight": "400",
            "--sjs-article-font-default-fontStyle": "normal",
            "--sjs-article-font-default-fontStretch": "normal",
            "--sjs-article-font-default-letterSpacing": "0",
            "--sjs-article-font-default-lineHeight": "28px",
            "--sjs-article-font-default-paragraphIndent": "0px",
            "--sjs-article-font-default-textCase": "none",
            "--sjs-general-backcolor-dim": "#303e4a",
            "--sjs-primary-backcolor": "#303e4a",
            "--sjs-primary-backcolor-dark": "#303e4a",
            "--sjs-primary-backcolor-light": "#303e4a",
            "--sjs-primary-background-500": "#303e4a",
            "--sjs-secondary-background-800": "#72b0be",
            "--sjs-secondary-background-700": "#72b0be",
            "--sjs-secondary-background-600": "#72b0be",
            "--sjs-secondary-background-500": "#72b0be",
            "--sjs-secondary-background-400": "#72b0be",
            "--sjs-secondary-background-300": "#72b0be",
            "--sjs-secondary-background-200": "#72b0be",
            "--sjs-secondary-background-100": "#72b0be",
            "--sjs-secondary-background-10": "#72b0be",
            "--sjs-secondary-background-25": "#72b0be",
            "--sjs-secondary-background-50": "#72b0be",
            "--sjs-primary-forecolor": "#bdd9e1",
            "--sjs-primary-forecolor-light": "#bdd9e1",
            "--sjs-special-red": "rgba(229, 10, 62, 1)",
            "--sjs-special-red-light": "rgba(229, 10, 62, 0.1)",
            "--sjs-font-surveytitle-family": "var(--font-mincho)",
            "--sjs-font-headertitle-family": "var(--font-mincho)",
            "--sjs-font-family": "var(--font-outfit)",
            "--ctr-font-family-code": "var(--font-outfit)",
            "--sjs-default-font-family": "var(--font-outfit)",
            "--sjs-font-headertitle-weight": "400",
            "--sjs-header-backcolor": "#fffff",
            "--ctr-survey-question-panel-toolbar-item-icon-color": "#09f1c7",
        },
        "themeName": "openlane",
        "colorPalette": "dark",
        "isPanelless": true,
}