const colors = {
  primary: 'var(--color-jade-400)',
  secondary: 'var(--color-jade-500)',
  yellow: 'var(--color-saffron-400)',
  surface: 'var(--color-background-dark)',
  background: 'var(--color-background-dark)',
  backgroundDim: 'var(--color-background-secondary)',
  borderColor: 'var(--color-border-dark)',
  backgroundLight: 'var(--color-jade-700)',
  textColor: 'var(--color-text-light)',
  textColorDim: 'var(--color-text-light)',
  inputPlaceholderColor: 'var(--color-text-light)',
  iconColor: 'var(--color-button-muted)',
}

const SJS_THEME = {
  '--foreground': colors.textColor,
  '--background': colors.background,
  '--background-dim-light': colors.surface,
  '--primary': colors.primary,
  '--secondary': colors.secondary,
  '--secondary-light': colors.secondary,
  '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.35)',
  '--sjs-shadow-inner': 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-border-default': 'rgba(255, 255, 255, 0.12)',
  '--sjs-border-light': 'rgba(255, 255, 255, 0.08)',
  '--sjs-general-backcolor': colors.background,
  '--sjs-general-backcolor-dark': 'rgba(52, 52, 52, 1)',
  '--sjs-general-backcolor-dim-light': 'rgba(43, 43, 43, 1)',
  '--sjs-general-backcolor-dim-dark': 'rgba(46, 46, 46, 1)',
  '--sjs-general-forecolor': colors.textColor,
  '--sjs-general-forecolor-light': colors.textColorDim,
  '--sjs-general-dim-forecolor': 'rgba(255, 255, 255, 0.79)',
  '--sjs-general-dim-forecolor-light': 'rgba(255, 255, 255, 0.45)',
  '--sjs-secondary-backcolor': colors.secondary,
  '--sjs-secondary-backcolor-light': colors.secondary,
  '--sjs-secondary-backcolor-semi-light': colors.secondary,
  '--sjs-secondary-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-secondary-forecolor-light': 'rgba(48, 48, 48, 0.25)',
  '--sjs-shadow-small-reset': '0px 0px 0px 0px rgba(0, 0, 0, 0.35)',
  '--sjs-shadow-medium': '0px 2px 6px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-inner-reset': 'inset 0px 0px 0px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-border-inside': 'rgba(255, 255, 255, 0.08)',
  '--sjs-special-red-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-green': 'rgba(36, 197, 164, 1)',
  '--sjs-special-green-light': 'rgba(36, 197, 164, 0.1)',
  '--sjs-special-green-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-blue': 'rgba(91, 151, 242, 1)',
  '--sjs-special-blue-light': 'rgba(91, 151, 242, 0.1)',
  '--sjs-special-blue-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-yellow': 'rgba(255, 152, 20, 1)',
  '--sjs-special-yellow-light': 'rgba(0, 255, 20, 0.1)',
  '--sjs-special-yellow-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-general-backcolor-dim': 'rgba(36, 36, 36, 1)',
  '--sjs-primary-backcolor': colors.primary,
  '--sjs-primary-backcolor-dark': 'rgba(0, 255, 0, 1)',
  '--sjs-primary-backcolor-light': 'rgba(0, 255, 0, 0.07)',
  '--sjs-primary-forecolor': 'rgba(32, 32, 32, 1)',
  '--sjs-primary-forecolor-light': 'rgba(32, 32, 32, 0.25)',
  '--sjs-special-red': 'rgba(254, 76, 108, 1)',
  '--sjs-special-red-light': 'rgba(254, 76, 108, 0.1)',
  '--sjs-questionpanel-hovercolor': colors.backgroundDim,
}

export const darkTheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'scroll',
  backgroundOpacity: 1,
  cssVariables: {
    ...SJS_THEME,
    '--ctr-actionbar-button-background-color-hovered': colors.backgroundDim,
    '--ctr-actionbar-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-actionbar-button-icon-color-with-text-disabled': colors.textColor,
    '--ctr-actionbar-button-icon-color': colors.textColor,
    '--ctr-actionbar-button-text-color-disabled': colors.textColor,
    '--ctr-actionbar-button-text-color': 'var(--sjs-primary-background-500)',
    '--ctr-button-background-color-cta-hovered': 'var(--sjs-primary-background-400)',
    '--ctr-button-background-color-cta': 'var(--sjs-primary-background-500)',
    '--ctr-button-background-color-danger': 'var(--sjs-semantic-red-background-500)',
    '--ctr-button-background-color-hovered': colors.backgroundDim,
    '--ctr-button-background-color': colors.background,
    '--ctr-button-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-button-contextual-button-background-color-focused': colors.backgroundDim,
    '--ctr-button-contextual-button-background-color-hovered': colors.backgroundDim,
    '--ctr-button-contextual-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-button-group-background-color-disabled': colors.background,
    '--ctr-button-group-background-color': colors.background,
    '--ctr-button-group-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-border-color': colors.backgroundDim,
    '--ctr-button-group-item-background-color-disabled': colors.background,
    '--ctr-button-group-item-background-color-hovered': colors.backgroundDim,
    '--ctr-button-group-item-background-color-selected-disabled': colors.backgroundDim,
    '--ctr-button-group-item-background-color-selected': colors.backgroundDim,
    '--ctr-button-group-item-background-color': colors.background,
    '--ctr-button-group-item-border-color': colors.backgroundDim,
    '--ctr-button-group-item-icon-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-item-icon-color': colors.iconColor,
    '--ctr-button-group-item-text-color-disabled': colors.textColor,
    '--ctr-button-group-item-text-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-item-text-color': colors.textColor,
    '--ctr-button-shadow-color': 'var(--ctr-shadow-small-color)',
    '--ctr-button-text-color-cta': 'var(--sjs-primary-foreground-100)',
    '--ctr-button-text-color-disabled': colors.textColor,
    '--ctr-button-text-color': 'var(--sjs-primary-background-500)',
    '--ctr-caption-with-actions-description-text-color-disabled': colors.textColor,
    '--ctr-caption-with-actions-description-text-color': colors.textColor,
    '--ctr-caption-with-actions-text-color-disabled': colors.textColor,
    '--ctr-caption-with-actions-text-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-checkbox-background-color-disabled': colors.background,
    '--ctr-checkbox-background-color-hovered': colors.background,
    '--ctr-checkbox-background-color-selected-hovered': colors.background,
    '--ctr-checkbox-background-color': colors.background,
    '--ctr-checkbox-border-color-disabled': colors.backgroundDim,
    '--ctr-checkbox-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-checkbox-border-color': colors.backgroundDim,
    '--ctr-checkbox-button-check-mark-color-disabled': colors.borderColor,
    '--ctr-checkbox-button-check-mark-color': 'var(--sjs-primary-background-500)',
    '--ctr-checkbox-description-text-color': colors.textColor,
    '--ctr-checkbox-text-color-disabled': colors.textColor,
    '--ctr-checkbox-text-color': colors.textColor,
    '--ctr-code-viewer-background-color': colors.background,
    '--ctr-code-viewer-line-number-panel-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-code-viewer-line-number-panel-text-color': 'var(--sjs-layer-2-foreground-50)',
    '--ctr-code-viewer-text-color': 'var(--sjs-code-gray-300)',
    '--ctr-collapse-button-background-color-hovered': colors.backgroundDim,
    '--ctr-collapse-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-collapse-button-icon-color': colors.iconColor,
    '--ctr-data-table-background-color': colors.backgroundDim,
    '--ctr-data-table-border-color': colors.borderColor,
    '--ctr-data-table-cell-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-data-table-cell-drop-down-arrow-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-data-table-cell-text-color-header': colors.inputPlaceholderColor,
    '--ctr-data-table-form-background-color': colors.background,
    '--ctr-data-table-form-border-color': colors.backgroundDim,
    '--ctr-data-table-row-background-color-drop-spot': colors.backgroundDim,
    '--ctr-data-table-row-background-color-header': colors.background,
    '--ctr-data-table-row-background-color': colors.background,
    '--ctr-data-table-row-border-color': colors.backgroundDim,
    '--ctr-data-table-row-drag-area-icon-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-editor-background-color-disabled': colors.background,
    '--ctr-editor-background-color': colors.surface,
    '--ctr-editor-border-color-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-editor-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-editor-border-color': colors.backgroundDim,
    '--ctr-editor-button-background-color-hovered': colors.background,
    '--ctr-editor-button-icon-color-disabled': colors.iconColor,
    '--ctr-editor-button-icon-color': colors.iconColor,
    '--ctr-editor-button-text-color': colors.textColor,
    '--ctr-editor-color-swatch-icon-height': 'var(--sjs-size-x2)',
    '--ctr-editor-color-swatch-icon-width': 'var(--sjs-size-x2)',
    '--ctr-editor-color-swatch-margin-left': 'var(--sjs-spacing-x150)',
    '--ctr-editor-content-icon-color': colors.iconColor,
    '--ctr-editor-content-text-color-disabled': colors.textColor,
    '--ctr-editor-content-text-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-editor-content-text-color': colors.textColor,
    '--ctr-editor-label-color-disabled': colors.textColor,
    '--ctr-editor-label-color': colors.inputPlaceholderColor,
    '--ctr-error-message-background-color': 'var(--sjs-semantic-red-background-10)',
    '--ctr-error-message-icon-color': 'var(--sjs-semantic-red-background-500)',
    '--ctr-error-message-text-color': colors.textColor,
    '--ctr-expression-item-background-color-action-hovered': 'var(--sjs-semantic-red-background-500)',
    '--ctr-expression-item-background-color-action': 'var(--sjs-semantic-red-background-10)',
    '--ctr-expression-item-background-color-button-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-expression-item-background-color-button': colors.backgroundDim,
    '--ctr-expression-item-background-color-conjunction-hovered': 'var(--sjs-semantic-yellow-background-500)',
    '--ctr-expression-item-background-color-conjunction': 'var(--sjs-semantic-yellow-background-10)',
    '--ctr-expression-item-background-color-operator-hovered': 'var(--sjs-semantic-yellow-background-500)',
    '--ctr-expression-item-background-color-operator': 'var(--sjs-semantic-yellow-background-10)',
    '--ctr-expression-item-background-color-parameter-error': colors.background,
    '--ctr-expression-item-background-color-parameter-hovered': 'var(--sjs-semantic-blue-background-500)',
    '--ctr-expression-item-background-color-parameter': 'var(--sjs-semantic-blue-background-10)',
    '--ctr-expression-item-text-color-action-hovered': 'var(--sjs-semantic-red-foreground-100)',
    '--ctr-expression-item-text-color-action': colors.textColor,
    '--ctr-expression-item-text-color-button-hovered': 'var(--sjs-primary-foreground-100)',
    '--ctr-expression-item-text-color-button': 'var(--sjs-primary-background-500)',
    '--ctr-expression-item-text-color-conjunction-hovered': 'var(--sjs-semantic-yellow-foreground-100)',
    '--ctr-expression-item-text-color-conjunction': colors.textColor,
    '--ctr-expression-item-text-color-function': colors.textColor,
    '--ctr-expression-item-text-color-operator-empty': colors.inputPlaceholderColor,
    '--ctr-expression-item-text-color-operator-hovered': 'var(--sjs-semantic-yellow-foreground-100)',
    '--ctr-expression-item-text-color-operator': colors.textColor,
    '--ctr-expression-item-text-color-parameter-empty': colors.inputPlaceholderColor,
    '--ctr-expression-item-text-color-parameter-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-expression-item-text-color-parameter-hovered': 'var(--sjs-semantic-blue-foreground-100)',
    '--ctr-expression-item-text-color-parameter': colors.textColor,
    '--ctr-font-family-code': 'var(--font-outfit)',
    '--ctr-font-family': 'var(--font-outfit)',
    '--sjs-default-font-family': 'var(--font-outfit)',
    '--sjs-font-family': 'var(--font-outfit)',
    '--ctr-image-gallery-item-title-color': colors.textColor,
    '--ctr-label-text-color-disabled': colors.textColor,
    '--ctr-label-text-color': colors.textColor,
    '--ctr-list-item-background-color-hovered': colors.backgroundDim,
    '--ctr-list-item-background-color-selected-submenu': colors.backgroundDim,
    '--ctr-list-item-background-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-color-swatch-corner-radius': 'var(--sjs-corner-radius-x05)',
    '--ctr-list-item-color-swatch-height': 'var(--sjs-spacing-x3)',
    '--ctr-list-item-color-swatch-width': 'var(--sjs-spacing-x4)',
    '--ctr-list-item-contextual-buttons-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-list-item-icon-color-disabled': colors.textColor,
    '--ctr-list-item-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-icon-color-selected-submenu': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-icon-color-selected': 'var(--sjs-primary-foreground-100)',
    '--ctr-list-item-icon-color': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-label-icon-color-disabled': colors.textColor,
    '--ctr-list-item-label-icon-color-hovered': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-list-item-submenu-arrow-color-hovered-item': colors.textColor,
    '--ctr-list-item-submenu-arrow-color-selected-item-submenu': colors.textColor,
    '--ctr-list-item-submenu-arrow-color': colors.textColor,
    '--ctr-list-item-text-color-hovered': colors.textColor,
    '--ctr-list-item-text-color-selected-submenu': colors.textColor,
    '--ctr-list-item-text-color-selected': 'var(--sjs-primary-foreground-100)',
    '--ctr-list-item-text-color': colors.textColor,
    '--ctr-list-search-border-color': colors.borderColor,
    '--ctr-list-search-icon-color': colors.textColor,
    '--ctr-list-search-text-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-menu-border-color': colors.borderColor,
    '--ctr-menu-item-background-color-hovered': colors.backgroundDim,
    '--ctr-menu-item-background-color': colors.background,
    '--ctr-menu-item-border-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-item-icon-color': colors.textColor,
    '--ctr-menu-item-text-color': colors.textColor,
    '--ctr-menu-toolbar-button-background-color-hovered': colors.backgroundDim,
    '--ctr-menu-toolbar-button-background-color-pressed': colors.backgroundDim,
    '--ctr-menu-toolbar-button-background-color-selected': colors.backgroundDim,
    '--ctr-menu-toolbar-button-icon-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-toolbar-button-icon-color': colors.textColor,
    '--ctr-menu-toolbar-button-text-color-secondary': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-menu-toolbar-button-text-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-toolbar-button-text-color': colors.textColor,
    '--ctr-notification-background-color-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-notification-background-color': colors.background,
    '--ctr-notification-text-color-error': 'var(--sjs-semantic-red-foreground-100)',
    '--ctr-notification-text-color': colors.textColor,
    '--ctr-page-banner-background-color': 'var(--sjs-secondary-background-500)',
    '--ctr-page-banner-text-color': 'var(--sjs-secondary-foreground-100)',
    '--ctr-page-navigator-button-background-color-hovered': colors.backgroundDim,
    '--ctr-page-navigator-button-background-color-pressed': colors.backgroundDim,
    '--ctr-page-navigator-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-page-navigator-button-icon-color': colors.iconColor,
    '--ctr-page-navigator-item-background-color-hovered': colors.background,
    '--ctr-page-navigator-item-dot-border-color-selected': colors.iconColor,
    '--ctr-page-navigator-item-dot-color-default': colors.iconColor,
    '--ctr-page-navigator-item-dot-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-page-navigator-item-dot-color-selected': 'var(--sjs-special-background)',
    '--ctr-page-navigator-item-text-color-hovered': colors.textColor,
    '--ctr-popup-background-color': colors.background,
    '--ctr-popup-description-color': colors.textColor,
    '--ctr-popup-haze-background-color': 'var(--sjs-special-haze)',
    '--ctr-popup-menu-background-color': colors.background,
    '--ctr-popup-menu-footer-background-color': colors.background,
    '--ctr-popup-menu-footer-border-color': colors.borderColor,
    '--ctr-popup-menu-pointer-color': colors.background,
    '--ctr-popup-message-color': colors.textColor,
    '--ctr-popup-shadow-2-color': 'var(--ctr-shadow-large-color)',
    '--ctr-popup-shadow-3-color': 'var(--ctr-shadow-x-large-color)',
    '--ctr-popup-title-color': colors.textColor,
    '--ctr-preview-pager-background-color': colors.background,
    '--ctr-preview-pager-border-color': colors.borderColor,
    '--ctr-property-grid-background-color': colors.background,
    '--ctr-property-grid-border-color': colors.borderColor,
    '--ctr-property-grid-chapter-caption-background-color-focused': colors.backgroundDim,
    '--ctr-property-grid-chapter-caption-background-color-hovered': colors.backgroundDim,
    '--ctr-property-grid-chapter-caption-background-color': colors.background,
    '--ctr-property-grid-chapter-caption-border-color': colors.borderColor,
    '--ctr-property-grid-chapter-caption-text-color-disabled': colors.textColor,
    '--ctr-property-grid-chapter-caption-text-color-selected': colors.textColor,
    '--ctr-property-grid-chapter-caption-text-color': colors.textColor,
    '--ctr-property-grid-form-background-color': colors.background,
    '--ctr-property-grid-group-caption-text-color': colors.textColor,
    '--ctr-property-grid-header-background-color': colors.background,
    '--ctr-property-grid-header-border-color': 'var(--sjs-primary-background-500)',
    '--ctr-property-grid-placeholder-text-description-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-property-grid-placeholder-text-title-color': colors.textColor,
    '--ctr-property-grid-search-background-color': colors.background,
    '--ctr-property-grid-search-border-color': colors.backgroundDim,
    '--ctr-property-grid-search-button-background-color-hovered': colors.background,
    '--ctr-property-grid-search-button-icon-color': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-count-text-color': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-icon-color': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-text-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-text-color': colors.textColor,
    '--ctr-property-grid-switcher-text-color': colors.textColor,
    '--ctr-property-grid-tabs-background-color': colors.background,
    '--ctr-property-grid-tabs-border-color': colors.borderColor,
    '--ctr-radio-button-background-color-disabled': colors.background,
    '--ctr-radio-button-background-color-hovered': colors.background,
    '--ctr-radio-button-background-color-selected-hovered': colors.background,
    '--ctr-radio-button-background-color': colors.background,
    '--ctr-radio-button-border-color-disabled': colors.backgroundDim,
    '--ctr-radio-button-border-color': colors.backgroundDim,
    '--ctr-radio-button-text-color-disabled': colors.textColor,
    '--ctr-radio-button-text-color': colors.textColor,
    '--ctr-scrollbar-background-color': colors.backgroundDim,
    '--ctr-search-button-background-color-hovered': colors.backgroundDim,
    '--ctr-search-icon-color': colors.textColor,
    '--ctr-separator-color': colors.borderColor,
    '--ctr-shadow-large-color': 'var(--sjs-special-glow)',
    '--ctr-shadow-medium-color': 'var(--sjs-special-glow)',
    '--ctr-shadow-small-color': 'var(--sjs-special-shadow)',
    '--ctr-shadow-x-large-color': 'var(--sjs-special-glow)',
    '--ctr-string-table-group-header-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-string-table-group-header-text-color': 'var(--sjs-layer-2-foreground-75)',
    '--ctr-string-table-header-background-color': colors.background,
    '--ctr-string-table-header-text-color': colors.iconColor,
    '--ctr-string-table-row-background-color': colors.background,
    '--ctr-string-table-row-border-color': colors.backgroundDim,
    '--ctr-string-table-row-expand-button-icon-color-default': colors.textColor,
    '--ctr-string-table-row-text-color-title': colors.textColor,
    '--ctr-surface-background-color': colors.surface,
    '--ctr-surface-placeholder-text-description-color': colors.textColorDim,
    '--ctr-surface-placeholder-text-title-color': colors.textColor,
    '--ctr-survey-action-button-background-color-hovered-negative': 'var(--sjs-semantic-red-background-10)',
    '--ctr-survey-action-button-background-color-hovered-positive': colors.backgroundDim,
    '--ctr-survey-action-button-icon-color-disabled': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-action-button-icon-color-negative': 'var(--sjs-semantic-red-background-500)',
    '--ctr-survey-action-button-icon-color-positive': 'var(--sjs-primary-background-500)',
    '--ctr-survey-action-button-text-color-disabled': colors.textColor,
    '--ctr-survey-action-button-text-color-positive': 'var(--sjs-primary-background-500)',
    '--ctr-survey-drop-indicator-color': 'var(--sjs-primary-background-500)',
    '--ctr-survey-header-logo-placeholder-background-color-hovered': colors.backgroundDim,
    '--ctr-survey-header-logo-placeholder-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-survey-header-logo-placeholder-icon-color': colors.inputPlaceholderColor,
    '--ctr-survey-header-text-description-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-header-text-title-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-image-picker-drop-spot-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-survey-info-panel-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-survey-info-panel-text-color': 'var(--sjs-layer-2-foreground-50)',
    '--ctr-survey-item-actionbar-drag-indicator-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-page-background-color-hovered': colors.background,
    '--ctr-survey-page-background-color-selected': colors.background,
    '--ctr-survey-page-border-color-hovered': 'var(--sjs-secondary-background-25)',
    '--ctr-survey-page-border-color-selected': 'var(--sjs-secondary-background-500)',
    '--ctr-survey-page-header-title-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-page-placeholder-text-color': colors.inputPlaceholderColor,
    '--ctr-survey-page-toolbar-item-background-color-hovered': colors.backgroundDim,
    '--ctr-survey-page-toolbar-item-background-color-selected': colors.backgroundDim,
    '--ctr-survey-page-toolbar-item-icon-color-pressed': colors.inputPlaceholderColor,
    '--ctr-survey-page-toolbar-item-text-color': colors.textColor,
    '--ctr-survey-placeholder-border-color': colors.borderColor,
    '--ctr-survey-placeholder-text-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-question-panel-border-color-hovered': 'var(--sjs-secondary-background-25)',
    '--ctr-survey-question-panel-border-color-selected': 'var(--sjs-secondary-background-500)',
    '--ctr-survey-question-panel-drag-area-drag-indicator-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-question-panel-toolbar-item-background-color-hovered': colors.backgroundDim,
    '--ctr-survey-question-panel-toolbar-item-background-color-selected': 'var(--sjs-secondary-background-10)',
    '--ctr-survey-question-panel-toolbar-item-icon-color': 'var(--sjs-secondary-background-500)',
    '--ctr-survey-question-panel-toolbar-item-text-color': colors.textColor,
    '--ctr-survey-radio-button-group-item-background-color-floating': colors.background,
    '--ctr-survey-radio-button-group-item-shadow-floating-1-color': 'var(--ctr-shadow-large-color)',
    '--ctr-survey-radio-button-group-item-shadow-floating-2-color': 'var(--ctr-shadow-medium-color)',
    '--ctr-text-decor-text-color-code': colors.textColor,
    '--ctr-toggle-button-background-color-checked-focused': 'var(--sjs-primary-foreground-100)',
    '--ctr-toggle-button-background-color-checked': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-background-color-hovered': colors.background,
    '--ctr-toggle-button-background-color': colors.background,
    '--ctr-toggle-button-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-border-color': colors.backgroundDim,
    '--ctr-toggle-button-label-text-color': colors.textColor,
    '--ctr-toggle-button-thumb-background-color-active': colors.iconColor,
    '--ctr-toggle-button-thumb-background-color-checked-focused': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-thumb-background-color-checked': 'var(--sjs-primary-foreground-100)',
    '--ctr-toggle-button-thumb-border-color': colors.backgroundDim,
    '--ctr-toolbox-background-color': colors.surface,
    '--ctr-toolbox-border-color': colors.borderColor,
    '--ctr-toolbox-button-background-color-hovered': colors.backgroundDim,
    '--ctr-toolbox-group-header-border-color': colors.borderColor,
    '--ctr-toolbox-group-header-expand-button-color': colors.textColor,
    '--ctr-toolbox-group-header-text-color': colors.textColor,
    '--ctr-toolbox-item-background-color-hovered': colors.backgroundDim,
    '--ctr-toolbox-item-background-color-pressed': colors.backgroundDim,
    '--ctr-toolbox-item-background-color-submenu': colors.background,
    '--ctr-toolbox-item-border-color-floating': 'var(--sjs-secondary-background-500)',
    '--ctr-toolbox-item-icon-color-disabled': colors.textColor,
    '--ctr-toolbox-item-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-toolbox-item-icon-color-pressed': colors.textColor,
    '--ctr-toolbox-item-icon-color': colors.iconColor,
    '--ctr-toolbox-item-shadow-hovered-1-color': '#00000000',
    '--ctr-toolbox-item-shadow-hovered-2-color': '#00000000',
    '--ctr-toolbox-item-shadow-pressed-color': '#00000000',
    '--ctr-toolbox-item-shadow-subitem-1-color': '#00000000',
    '--ctr-toolbox-item-shadow-subitem-2-color': '#00000000',
    '--ctr-toolbox-item-submenu-button-background-color-hovered': colors.backgroundLight,
    '--ctr-toolbox-item-submenu-button-background-color': colors.background,
    '--ctr-toolbox-item-submenu-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-item-text-color-hovered': colors.textColor,
    '--ctr-toolbox-item-text-color-pressed': colors.textColor,
    '--ctr-toolbox-item-text-color-submenu': colors.textColor,
    '--ctr-toolbox-item-text-color': colors.textColor,
    '--ctr-toolbox-search-clear-button-background-color-hovered': 'var(--sjs-semantic-red-background-10)',
    '--ctr-toolbox-search-clear-button-icon-color-hovered': 'var(--sjs-semantic-red-background-500)',
    '--ctr-toolbox-search-clear-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-search-icon-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-search-icon-color': 'var(--sjs-primary-background-500)',
    '--ctr-toolbox-search-text-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-search-text-color': colors.textColor,
    '--ctr-toolbox-separator-color': colors.borderColor,
    '--ctr-toolbox-shadow-floating-1-color': 'var(--ctr-shadow-medium-color)',
    '--ctr-toolbox-shadow-floating-2-color': 'var(--ctr-shadow-large-color)',
    '--ctr-toolbox-submenu-background-color': colors.background,
    '--ctr-toolbox-submenu-shadow-1-color': 'var(--ctr-shadow-medium-color)',
    '--ctr-toolbox-submenu-shadow-2-color': 'var(--ctr-shadow-large-color)',
    '--ctr-tooltip-background-color': colors.background,
    '--ctr-tooltip-shadow-1-color': 'var(--ctr-shadow-medium-color)',
    '--ctr-tooltip-shadow-2-color': 'var(--ctr-shadow-small-color)',
    '--lbr-action-button-icon-color-negative': 'var(--sjs-semantic-red-background-500)',
    '--lbr-shadow-inner-color': 'var(--sjs-special-shadow)',
    '--lbr-shadow-large-color': 'var(--sjs-special-glow)',
    '--lbr-shadow-medium-color': 'var(--sjs-special-glow)',
    '--lbr-shadow-small-color': 'var(--sjs-special-shadow)',
    '--lbr-shadow-x-large-color': 'var(--sjs-special-glow)',
  },
  themeName: 'openlane',
  colorPalette: 'light',
  isPanelless: true,
}
