import { ITheme } from "survey-core";

export const lightTheme : ITheme = {
    "backgroundImageFit": "cover",
    "backgroundImageAttachment": "scroll",
    "backgroundOpacity": 1,
    "cssVariables": {
            "--sjs-general-forecolor": "#082930",
            "--ctr-list-item-background-color-selected": "#09f1c7",
            "--ctr-menu-item-background-color-hovered": "#00deb7",
            "--sjs-questionpanel-hovercolor": "#f5f9fa",
            "--ctr-property-grid-chapter-caption-text-color-selected": "#082930",
            "--ctr-survey-question-panel-toolbar-item-text-color": "#082930",
            "--ctr-survey-header-logo-placeholder-icon-color": "#e9f1f5",
            "--ctr-list-item-text-color": "#082930",
            "--ctr-list-item-text-color-selected": "#082930",
            "--ctr-menu-toolbar-button-background-color-pressed": "#09f1c7",
            "--ctr-menu-toolbar-button-text-color": "#082930",
            "--ctr-menu-toolbar-button-text-color-selected": "#082930",
            "--sjs-corner-radius": "4px",
            "--sjs-base-unit": "8px",
            "--sjs-font-pagetitle-color": "#082930",
            "--sjs-font-pagedescription-color":  "#082930",
            "--sjs-font-surveytitle-color": "#082930",
            "--sjs-font-surveydescription-color": "#bdd9e1",
            "--sjs-font-questiontitle-color": "#082930",
            "--sjs-font-questiondescription-color": "#082930",
            "--sjs-font-editorfont-color": "#082930",
            "--ctr-editor-content-text-color": "#082930",
            "--ctr-survey-header-text-title-color-placeholder": "#082930",
            "--sjs-editorpanel-backcolor": "#ffffff",
            "--sjs-font-editorfont-placeholdercolor": "#082930",
            "--sjs-shadow-small": "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-inner": "inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-default": "#c2d7df",
            "--sjs-border-light": "#c2d7df",
            "--ctr-menu-item-border-color-selected": "#09f1c7",
            "--sjs-general-backcolor": "#e9f1f5",
            "--sjs-general-backcolor-dark": "#e9f1f5",
            "--sjs-questionpanel-backcolor": "#ffffff",
            "--sjs-question-background": "#ffffff",
            "--sjs-editor-background": "#ffffff",
            "--ctr-property-grid-form-background-color": "#e9f1f5",
            "--sjs-general-dim-forecolor": "#082930",
            "--sjs-general-dim-forecolor-light": "#ffffff",
            "--ctr-survey-page-header-title-color-placeholder": "#082930",
            "--foreground": "#e9f1f5",
            "--primary-foreground": "#e9f1f5",
            "--ctr-property-grid-search-text-color": "#082930",
            "--sjs-secondary-backcolor": "#09f1c7",
            "--sjs-secondary-backcolor-light": "#09f1c7",
            "--sjs-secondary-backcolor-semi-light": "#09f1c7",
            "--sjs-secondary-forecolor": "#e9f1f5",
            "--sjs-secondary-forecolor-25": "#e9f1f5",
            "--sjs-secondary-forecolor-50": "#e9f1f5",
            "--sjs-secondary-foreground-100": "#e9f1f5",
            "--sjs-secondary-foreground-200": "#e9f1f5",
            "--sjs-secondary-foreground-300": "#e9f1f5",
            "--sjs-secondary-foreground-400": "#e9f1f5",
            "--sjs-secondary-foreground-500": "#e9f1f5",
            "--sjs-secondary-foreground-600": "#e9f1f5",
            "--sjs-secondary-foreground-700": "#e9f1f5",
            "--sjs-secondary-foreground-800": "#e9f1f5",
            "--sjs-secondary-foreground-900": "#e9f1f5",
            "--sjs-secondary-forecolor-light": "#e9f1f5",
            "--sjs-layer-1-foreground-100 " : "#e9f1f5",
            "--sjs-layer-1-foreground-200 " : "#e9f1f5",
            "--sjs-layer-1-foreground-300 " : "#e9f1f5",
            "--sjs-layer-1-foreground-400 " : "#e9f1f5",
            "--sjs-layer-1-foreground-500 " : "#e9f1f5",
            "--sjs-layer-1-foreground-600 " : "#e9f1f5",
            "--sjs-layer-1-foreground-700 " : "#e9f1f5",
            "--sjs-layer-1-foreground-800 " : "#e9f1f5",
            "--sjs-shadow-small-reset": "0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-shadow-medium": "0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
            "--sjs-shadow-inner-reset": "inset 0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
            "--sjs-border-inside": "#c2d7df",
            "--sjs-special-red-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-green": "rgba(25, 179, 148, 1)",
            "--sjs-special-green-light": "rgba(25, 179, 148, 0.1)",
            "--sjs-special-green-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-blue": "rgba(67, 127, 217, 1)",
            "--sjs-special-blue-light": "rgba(67, 127, 217, 0.1)",
            "--sjs-special-blue-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
            "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
            "--sjs-special-yellow-forecolor": "rgba(255, 255, 255, 1)",
            "--sjs-article-font-xx-large-textDecoration": "none",
            "--sjs-article-font-xx-large-fontWeight": "400",
            "--sjs-article-font-xx-large-fontStyle": "normal",
            "--sjs-article-font-xx-large-fontStretch": "normal",
            "--sjs-article-font-xx-large-letterSpacing": "0",
            "--sjs-article-font-xx-large-lineHeight": "64px",
            "--sjs-article-font-xx-large-paragraphIndent": "0px",
            "--sjs-article-font-xx-large-textCase": "none",
            "--sjs-article-font-x-large-textDecoration": "none",
            "--sjs-article-font-x-large-fontWeight": "400",
            "--sjs-article-font-x-large-fontStyle": "normal",
            "--sjs-article-font-x-large-fontStretch": "normal",
            "--sjs-article-font-x-large-letterSpacing": "0",
            "--sjs-article-font-x-large-lineHeight": "56px",
            "--sjs-article-font-x-large-paragraphIndent": "0px",
            "--sjs-article-font-x-large-textCase": "none",
            "--sjs-article-font-large-textDecoration": "none",
            "--sjs-article-font-large-fontWeight": "400",
            "--sjs-article-font-large-fontStyle": "normal",
            "--sjs-article-font-large-fontStretch": "normal",
            "--sjs-article-font-large-letterSpacing": "0",
            "--sjs-article-font-large-lineHeight": "40px",
            "--sjs-article-font-large-paragraphIndent": "0px",
            "--sjs-article-font-large-textCase": "none",
            "--sjs-article-font-medium-textDecoration": "none",
            "--sjs-article-font-medium-fontWeight": "400",
            "--sjs-article-font-medium-fontStyle": "normal",
            "--sjs-article-font-medium-fontStretch": "normal",
            "--sjs-article-font-medium-letterSpacing": "0",
            "--sjs-article-font-medium-lineHeight": "32px",
            "--sjs-article-font-medium-paragraphIndent": "0px",
            "--sjs-article-font-medium-textCase": "none",
            "--sjs-article-font-default-textDecoration": "none",
            "--sjs-article-font-default-fontWeight": "400",
            "--sjs-article-font-default-fontStyle": "normal",
            "--sjs-article-font-default-fontStretch": "normal",
            "--sjs-article-font-default-letterSpacing": "0",
            "--sjs-article-font-default-lineHeight": "28px",
            "--sjs-article-font-default-paragraphIndent": "0px",
            "--sjs-article-font-default-textCase": "none",
            "--sjs-general-backcolor-dim": "#e9f1f5",
            "--sjs-aquamarine-backcolor": "#082930",
            "--sjs-aquamarine-backcolor-dark": "#09f1c7",
            "--sjs-secondary-background-800": "#007364",
            "--sjs-secondary-background-700": "#00927d",
            "--sjs-secondary-background-600": "#00b696",
            "--sjs-secondary-background-500": "#00deb7",
            "--sjs-secondary-background-400": "#09f1c7",
            "--sjs-secondary-background-300": "#53ffdd",
            "--sjs-secondary-background-200": "#96ffe4",
            "--sjs-secondary-background-100": "#c8ffef",
            "--sjs-secondary-background-10": "#c8ffef",
            "--sjs-secondary-background-25": "#c8ffef",
            "--sjs-secondary-background-50": "#c8ffef",
            "--sjs-primary-foreground-25": "#082930",
            "--sjs-primary-foreground-50": "#082930",
            "--sjs-primary-foreground-100": "#082930",
            "--sjs-primary-foreground-200": "#082930",
            "--sjs-primary-foreground-300": "#082930",
            "--sjs-primary-foreground-400": "#082930",
            "--sjs-primary-foreground-500": "#082930",
            "--sjs-primary-foreground-600": "#082930",
            "--sjs-primary-foreground-700": "#082930",
            "--sjs-primary-foreground-800": "#082930",
            "--sjs-primary-foreground-900": "#082930",
            "--sjs-aquamarine-backcolor-light": "#09f1c7",
            "--sjs-aquamarine-background-500": "#09f1c7",
            "--sjs-aquamarine-forecolor": "#e9f1f5",
            "--sjs-aquamarine-forecolor-light": "#e9f1f5",
            "--sjs-special-red": "rgba(229, 10, 62, 1)",
            "--sjs-special-red-light": "rgba(229, 10, 62, 0.1)",
            "--sjs-font-surveytitle-family": "var(--font-mincho)",
            "--sjs-font-headertitle-family": "var(--font-mincho)",
            "--ctr-font-family-code": "var(--font-outfit)",
            "--ctr-font-family": "var(--font-outfit)",
            "--sjs-default-font-family": "var(--font-outfit)",
            "--sjs-font-family": "var(--font-outfit)",
            "--sjs-font-headertitle-weight": "400",
            "--sjs-header-backcolor": "#082930",
            "--ctr-survey-question-panel-toolbar-item-icon-color": "#09f1c7",
        },
        "themeName": "openlane",
        "colorPalette": "light",
        "isPanelless": true,
}
