import { ITheme } from 'survey-core'

const colors = {
  primary: '#60e8c9',
  secondary: '#2dcdad',
  yellow: '#ff842c',
  surface: '#09151d',
  background: '#09151d',
  backgroundDim: '#162431',
  borderColor: '#304757',
  backgroundLight: '#233440',
  textColor: '#ffffff',
  textColorDim: '#9aa5b0',
  inputPlaceholderColor: '#9aa5b0',
  iconColor: '#4c5e69',
}

// https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/themes/predefined-themes/default/dark.css
// exported from https://surveyjs.io/create-free-survey - use the theme tab, go to theme,then use the export button
const SJS_THEME = {
  '--foreground': colors.textColor,
  '--background': colors.background,
  '--background-dim-light': colors.surface,
  '--primary': colors.primary,
  '--secondary': colors.secondary,
  '--secondary-light': colors.secondary,
  '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.35)',
  '--sjs-shadow-inner': 'inset 0px 1px 2px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-border-default': 'rgba(255, 255, 255, 0.12)',
  '--sjs-border-light': 'rgba(255, 255, 255, 0.08)',
  '--sjs-general-backcolor': colors.background,
  '--sjs-general-backcolor-dark': 'rgba(52, 52, 52, 1)',
  '--sjs-general-backcolor-dim-light': 'rgba(43, 43, 43, 1)',
  '--sjs-general-backcolor-dim-dark': 'rgba(46, 46, 46, 1)',
  '--sjs-general-forecolor': colors.textColor,
  '--sjs-general-forecolor-light': colors.textColorDim,
  '--sjs-general-dim-forecolor': 'rgba(255, 255, 255, 0.79)',
  '--sjs-general-dim-forecolor-light': 'rgba(255, 255, 255, 0.45)',
  '--sjs-secondary-backcolor': colors.secondary,
  '--sjs-secondary-backcolor-light': colors.secondary,
  '--sjs-secondary-backcolor-semi-light': colors.secondary,
  '--sjs-secondary-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-secondary-forecolor-light': 'rgba(48, 48, 48, 0.25)',
  '--sjs-shadow-small-reset': '0px 0px 0px 0px rgba(0, 0, 0, 0.35)',
  '--sjs-shadow-medium': '0px 2px 6px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-inner-reset': 'inset 0px 0px 0px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-border-inside': 'rgba(255, 255, 255, 0.08)',
  '--sjs-special-red-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-green': 'rgba(36, 197, 164, 1)',
  '--sjs-special-green-light': 'rgba(36, 197, 164, 0.1)',
  '--sjs-special-green-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-blue': 'rgba(91, 151, 242, 1)',
  '--sjs-special-blue-light': 'rgba(91, 151, 242, 0.1)',
  '--sjs-special-blue-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-special-yellow': 'rgba(255, 152, 20, 1)',
  '--sjs-special-yellow-light': 'rgba(0, 255, 20, 0.1)',
  '--sjs-special-yellow-forecolor': 'rgba(48, 48, 48, 1)',
  '--sjs-general-backcolor-dim': 'rgba(36, 36, 36, 1)',
  '--sjs-primary-backcolor': colors.primary,
  '--sjs-primary-backcolor-dark': '#2dcdad',
  '--sjs-primary-backcolor-light': 'rgba(96, 232, 201, 0.07)',
  '--sjs-primary-forecolor': '#ffffff',
  '--sjs-primary-forecolor-light': 'rgba(255, 255, 255, 0.25)',
  '--sjs-special-red': 'rgba(254, 76, 108, 1)',
  '--sjs-special-red-light': 'rgba(254, 76, 108, 0.1)',
  '--sjs-questionpanel-hovercolor': colors.backgroundDim,
  '--sjs-questionpanel-backcolor': colors.backgroundLight,
  '--sjs-question-background': colors.backgroundLight,
  '--sjs-editor-background': colors.backgroundLight,
  '--sjs-editorpanel-backcolor': colors.backgroundLight,
  '--sjs-font-pagetitle-color': colors.textColor,
  '--sjs-font-pagedescription-color': colors.textColorDim,
  '--sjs-font-surveytitle-color': colors.textColor,
  '--sjs-font-surveydescription-color': colors.textColorDim,
  '--sjs-font-questiontitle-color': colors.textColor,
  '--sjs-font-questiondescription-color': colors.textColorDim,
  '--sjs-font-editorfont-color': colors.textColor,
  '--sjs-font-editorfont-placeholdercolor': colors.inputPlaceholderColor,
  '--sjs-secondary-background-800': '#005e4d',
  '--sjs-secondary-background-700': '#00795f',
  '--sjs-secondary-background-600': '#009975',
  '--sjs-secondary-background-500': '#2dcdad',
  '--sjs-secondary-background-400': '#60e8c9',
  '--sjs-secondary-background-300': '#9af5dd',
  '--sjs-secondary-background-200': '#c8ffef',
  '--sjs-secondary-background-100': '#e0fff7',
  '--sjs-secondary-background-10': '#e0fff7',
  '--sjs-secondary-background-25': '#e0fff7',
  '--sjs-secondary-background-50': '#e0fff7',
  '--sjs-primary-foreground-25': '#ffffff',
  '--sjs-primary-foreground-50': '#ffffff',
  '--sjs-primary-foreground-100': '#ffffff',
  '--sjs-primary-foreground-200': '#ffffff',
  '--sjs-primary-foreground-300': '#ffffff',
  '--sjs-primary-foreground-400': '#ffffff',
  '--sjs-primary-foreground-500': '#ffffff',
  '--sjs-primary-foreground-600': '#ffffff',
  '--sjs-primary-foreground-700': '#ffffff',
  '--sjs-primary-foreground-800': '#ffffff',
  '--sjs-primary-foreground-900': '#ffffff',
  '--sjs-primary-background-500': '#60e8c9',
  '--sjs-layer-1-foreground-100 ': '#ffffff',
  '--sjs-layer-1-foreground-200 ': '#ffffff',
  '--sjs-layer-1-foreground-300 ': '#ffffff',
  '--sjs-layer-1-foreground-400 ': '#ffffff',
  '--sjs-layer-1-foreground-500 ': '#ffffff',
  '--sjs-layer-1-foreground-600 ': '#ffffff',
  '--sjs-layer-1-foreground-700 ': '#ffffff',
  '--sjs-layer-1-foreground-800 ': '#ffffff',
  '--sjs-font-surveytitle-family': 'var(--font-mincho)',
  '--sjs-font-headertitle-family': 'var(--font-mincho)',
  '--sjs-font-headertitle-weight': '400',
  '--sjs-header-backcolor': '#09151d',
  '--sjs-article-font-xx-large-textDecoration': 'none',
  '--sjs-article-font-xx-large-fontWeight': '400',
  '--sjs-article-font-xx-large-fontStyle': 'normal',
  '--sjs-article-font-xx-large-fontStretch': 'normal',
  '--sjs-article-font-xx-large-letterSpacing': '0',
  '--sjs-article-font-xx-large-lineHeight': '64px',
  '--sjs-article-font-xx-large-paragraphIndent': '0px',
  '--sjs-article-font-xx-large-textCase': 'none',
  '--sjs-article-font-x-large-textDecoration': 'none',
  '--sjs-article-font-x-large-fontWeight': '400',
  '--sjs-article-font-x-large-fontStyle': 'normal',
  '--sjs-article-font-x-large-fontStretch': 'normal',
  '--sjs-article-font-x-large-letterSpacing': '0',
  '--sjs-article-font-x-large-lineHeight': '56px',
  '--sjs-article-font-x-large-paragraphIndent': '0px',
  '--sjs-article-font-x-large-textCase': 'none',
  '--sjs-article-font-large-textDecoration': 'none',
  '--sjs-article-font-large-fontWeight': '400',
  '--sjs-article-font-large-fontStyle': 'normal',
  '--sjs-article-font-large-fontStretch': 'normal',
  '--sjs-article-font-large-letterSpacing': '0',
  '--sjs-article-font-large-lineHeight': '40px',
  '--sjs-article-font-large-paragraphIndent': '0px',
  '--sjs-article-font-large-textCase': 'none',
  '--sjs-article-font-medium-textDecoration': 'none',
  '--sjs-article-font-medium-fontWeight': '400',
  '--sjs-article-font-medium-fontStyle': 'normal',
  '--sjs-article-font-medium-fontStretch': 'normal',
  '--sjs-article-font-medium-letterSpacing': '0',
  '--sjs-article-font-medium-lineHeight': '32px',
  '--sjs-article-font-medium-paragraphIndent': '0px',
  '--sjs-article-font-medium-textCase': 'none',
  '--sjs-article-font-default-textDecoration': 'none',
  '--sjs-article-font-default-fontWeight': '400',
  '--sjs-article-font-default-fontStyle': 'normal',
  '--sjs-article-font-default-fontStretch': 'normal',
  '--sjs-article-font-default-letterSpacing': '0',
  '--sjs-article-font-default-lineHeight': '28px',
  '--sjs-article-font-default-paragraphIndent': '0px',
  '--sjs-article-font-default-textCase': 'none',
  // ' --sjs-layer-1-background-500': colors.background,
  // '--lbr-question-panel-background-color': colors.background,
  '--lbr-question-panel-background-color': colors.background,
}

// this theme is from the suveyjs creator colors
// the default theme variables are here: https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/themes/default.ts
export const darkTheme: ITheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'scroll',
  backgroundOpacity: 1,
  cssVariables: {
    ...SJS_THEME,
    '--ctr-actionbar-button-background-color-hovered': colors.backgroundDim,
    // "--ctr-actionbar-button-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-actionbar-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-actionbar-button-icon-color-with-text-disabled': colors.textColor,
    '--ctr-actionbar-button-icon-color': colors.textColor,
    // "--ctr-actionbar-button-icon-height-small": "var(--sjs-size-x2)",
    // "--ctr-actionbar-button-icon-height": "var(--sjs-size-x3)",
    // "--ctr-actionbar-button-icon-width-small": "var(--sjs-size-x2)",
    // "--ctr-actionbar-button-icon-width": "var(--sjs-size-x3)",
    // "--ctr-actionbar-button-opacity-disabled": 0.25,
    // "--ctr-actionbar-button-opacity-muted": 0.35,
    // "--ctr-actionbar-button-opacity-pressed": 0.5,
    // "--ctr-actionbar-button-padding-bottom-large-icon": "var(--sjs-spacing-x1)",
    // "--ctr-actionbar-button-padding-bottom-medium-text": "var(--sjs-spacing-x05)",
    // "--ctr-actionbar-button-padding-bottom-small-icon": "var(--sjs-spacing-x05)",
    // "--ctr-actionbar-button-padding-left-large-icon": "var(--sjs-spacing-x1)",
    // "--ctr-actionbar-button-padding-left-medium-text": "var(--sjs-spacing-x2)",
    // "--ctr-actionbar-button-padding-left-small-icon": "var(--sjs-spacing-x05)",
    // "--ctr-actionbar-button-padding-right-large-icon": "var(--sjs-spacing-x1)",
    // "--ctr-actionbar-button-padding-right-medium-text": "var(--sjs-spacing-x2)",
    // "--ctr-actionbar-button-padding-right-small-icon": "var(--sjs-spacing-x05)",
    // "--ctr-actionbar-button-padding-top-large-icon": "var(--sjs-spacing-x1)",
    // "--ctr-actionbar-button-padding-top-medium-text": "var(--sjs-spacing-x05)",
    // "--ctr-actionbar-button-padding-top-small-icon": "var(--sjs-spacing-x05)",
    '--ctr-actionbar-button-text-color-disabled': colors.textColor,
    '--ctr-actionbar-button-text-color': 'var(--sjs-primary-background-500)',
    '--ctr-button-background-color-cta-hovered': 'var(--sjs-primary-background-400)',
    '--ctr-button-background-color-cta': 'var(--sjs-primary-background-500)',
    '--ctr-button-background-color-danger': 'var(--sjs-semantic-red-background-500)',
    '--ctr-button-background-color-hovered': colors.backgroundDim,
    '--ctr-button-background-color': colors.background,
    '--ctr-button-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-button-contextual-button-background-color-focused': colors.backgroundDim,
    '--ctr-button-contextual-button-background-color-hovered': colors.backgroundDim,
    // "--ctr-button-contextual-button-corner-radius": "var(--sjs-corner-radius-x05)",
    '--ctr-button-contextual-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-button-contextual-button-icon-height": "var(--sjs-size-x3)",
    // "--ctr-button-contextual-button-icon-width": "var(--sjs-size-x3)",
    // "--ctr-button-contextual-button-margin-horizontal": "var(--sjs-spacing-x1)",
    // "--ctr-button-contextual-button-margin-vertical": "var(--sjs-spacing-x1)",
    // "--ctr-button-contextual-button-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-button-contextual-button-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-button-contextual-button-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-button-contextual-button-padding-top": "var(--sjs-spacing-x1)",
    // "--ctr-button-corner-radius-small": "var(--sjs-corner-radius-x075)",
    // "--ctr-button-corner-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-button-gap": "var(--sjs-spacing-x4)",
    '--ctr-button-group-background-color-disabled': colors.background,
    '--ctr-button-group-background-color': colors.background,
    '--ctr-button-group-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-border-color': colors.backgroundDim,
    // "--ctr-button-group-border-width-focused": "var(--sjs-stroke-x2)",
    // "--ctr-button-group-border-width": "var(--sjs-stroke-x1)",
    // "--ctr-button-group-corner-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-button-group-gap": "var(--sjs-spacing-x05)",
    '--ctr-button-group-item-background-color-disabled': colors.background,
    '--ctr-button-group-item-background-color-hovered': colors.backgroundDim,
    '--ctr-button-group-item-background-color-selected-disabled': colors.backgroundDim,
    '--ctr-button-group-item-background-color-selected': colors.backgroundDim,
    '--ctr-button-group-item-background-color': colors.background,
    '--ctr-button-group-item-border-color': colors.backgroundDim,
    // "--ctr-button-group-item-border-width-selected-disabled": "0px",
    // "--ctr-button-group-item-border-width-selected": "var(--sjs-stroke-x1)",
    // "--ctr-button-group-item-border-width": "0px",
    // "--ctr-button-group-item-corner-radius": "var(--sjs-corner-radius-x05)",
    '--ctr-button-group-item-icon-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-item-icon-color': colors.iconColor,
    // "--ctr-button-group-item-padding-horizontal": "var(--sjs-spacing-x2)",
    // "--ctr-button-group-item-padding-vertical": "var(--sjs-spacing-x1)",
    '--ctr-button-group-item-text-color-disabled': colors.textColor,
    '--ctr-button-group-item-text-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-button-group-item-text-color': colors.textColor,
    // "--ctr-button-group-item-text-opacity-disabled": 0.25,
    // "--ctr-button-group-padding": "var(--sjs-spacing-x05)",
    // "--ctr-button-padding-horizontal-small": "var(--sjs-spacing-x4)",
    // "--ctr-button-padding-vertical-small": "var(--sjs-spacing-x150)",
    // "--ctr-button-shadow-blur": "var(--ctr-shadow-small-blur)",
    '--ctr-button-shadow-color': 'var(--ctr-shadow-small-color)',
    // "--ctr-button-shadow-offset-x": "var(--ctr-shadow-small-offset-x)",
    // "--ctr-button-shadow-offset-y": "var(--ctr-shadow-small-offset-y)",
    // "--ctr-button-shadow-spread": "var(--ctr-shadow-small-spread)",
    '--ctr-button-text-color-cta': 'var(--sjs-primary-foreground-100)',
    '--ctr-button-text-color-disabled': colors.textColor,
    '--ctr-button-text-color': 'var(--sjs-primary-background-500)',
    // "--ctr-button-text-opacity-disabled": 0.25,
    '--ctr-caption-with-actions-description-text-color-disabled': colors.textColor,
    '--ctr-caption-with-actions-description-text-color': colors.textColor,
    '--ctr-caption-with-actions-text-color-disabled': colors.textColor,
    '--ctr-caption-with-actions-text-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-checkbox-background-color-disabled': colors.background,
    '--ctr-checkbox-background-color-hovered': colors.background,
    '--ctr-checkbox-background-color-selected-hovered': colors.background,
    '--ctr-checkbox-background-color': colors.background,
    '--ctr-checkbox-border-color-disabled': colors.backgroundDim,
    '--ctr-checkbox-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-checkbox-border-color': colors.backgroundDim,
    // "--ctr-checkbox-border-width": "var(--sjs-stroke-x1)",
    '--ctr-checkbox-button-check-mark-color-disabled': colors.borderColor,
    '--ctr-checkbox-button-check-mark-color': 'var(--sjs-primary-background-500)',
    // "--ctr-checkbox-button-check-mark-height": "var(--sjs-size-x2)",
    // "--ctr-checkbox-button-check-mark-width": "var(--sjs-size-x2)",
    // "--ctr-checkbox-button-height": "var(--sjs-size-x3)",
    // "--ctr-checkbox-button-width": "var(--sjs-size-x3)",
    // "--ctr-checkbox-corner-radius": "var(--sjs-corner-radius-x05)",
    '--ctr-checkbox-description-text-color': colors.textColor,
    // "--ctr-checkbox-description-text-margin-left": "var(--sjs-spacing-x4)",
    // "--ctr-checkbox-gap": "var(--sjs-spacing-x1)",
    // "--ctr-checkbox-list-gap-vertical": "var(--sjs-spacing-x2)",
    '--ctr-checkbox-text-color-disabled': colors.textColor,
    '--ctr-checkbox-text-color': colors.textColor,
    '--ctr-code-viewer-background-color': colors.background,
    // "--ctr-code-viewer-code-error-row-icon-height": "var(--sjs-size-x2)",
    // "--ctr-code-viewer-code-error-row-icon-width": "var(--sjs-size-x2)",
    '--ctr-code-viewer-line-number-panel-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-code-viewer-line-number-panel-text-color': 'var(--sjs-layer-2-foreground-50)',
    '--ctr-code-viewer-text-color': 'var(--sjs-code-gray-300)',
    '--ctr-collapse-button-background-color-hovered': colors.backgroundDim,
    // "--ctr-collapse-button-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-collapse-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-collapse-button-icon-color': colors.iconColor,
    // "--ctr-corner-radius-unit": "8px",
    '--ctr-data-table-background-color': colors.backgroundDim,
    '--ctr-data-table-border-color': colors.borderColor,
    // "--ctr-data-table-border-width": "var(--sjs-stroke-x1)",
    '--ctr-data-table-cell-border-color-focused': 'var(--sjs-primary-background-500)',
    // "--ctr-data-table-cell-corner-radius-focused": "var(--sjs-corner-radius-x075)",
    '--ctr-data-table-cell-drop-down-arrow-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-data-table-cell-drop-down-arrow-height": "var(--sjs-size-x3)",
    // "--ctr-data-table-cell-drop-down-arrow-opacity": 0.5,
    // "--ctr-data-table-cell-drop-down-arrow-width": "var(--sjs-size-x3)",
    // "--ctr-data-table-cell-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-data-table-cell-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-data-table-cell-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-data-table-cell-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-data-table-cell-text-color-header': colors.inputPlaceholderColor,
    // "--ctr-data-table-corner-radius": "var(--sjs-corner-radius-x075)",
    '--ctr-data-table-form-background-color': colors.background,
    '--ctr-data-table-form-border-color': colors.backgroundDim,
    // "--ctr-data-table-placeholder-corner-radius": "var(--sjs-corner-radius-x075)",
    '--ctr-data-table-row-background-color-drop-spot': colors.backgroundDim,
    '--ctr-data-table-row-background-color-header': colors.background,
    '--ctr-data-table-row-background-color': colors.background,
    '--ctr-data-table-row-border-color': colors.backgroundDim,
    // "--ctr-data-table-row-border-width-last-row": "0px",
    // "--ctr-data-table-row-border-width": "var(--sjs-stroke-x1)",
    // "--ctr-data-table-row-corner-radius-floating": "var(--sjs-corner-radius-x05)",
    '--ctr-data-table-row-drag-area-icon-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-data-table-row-padding-bottom-header": "var(--sjs-spacing-x1)",
    // "--ctr-data-table-row-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-data-table-row-padding-left": "0px",
    // "--ctr-data-table-row-padding-right": "var(--sjs-spacing-x05)",
    // "--ctr-data-table-row-padding-top-header": "var(--sjs-spacing-x1)",
    // "--ctr-data-table-row-padding-top": "var(--sjs-spacing-x05)",
    // "--ctr-data-table-row-shadow-floating-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-data-table-row-shadow-floating-1-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-data-table-row-shadow-floating-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-data-table-row-shadow-floating-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-data-table-row-shadow-floating-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-data-table-row-shadow-floating-2-blur": "var(--ctr-shadow-large-blur)",
    '--ctr-data-table-row-shadow-floating-2-color': 'var(--ctr-shadow-large-color)',
    // "--ctr-data-table-row-shadow-floating-2-offset-x": "var(--ctr-shadow-large-offset-x)",
    // "--ctr-data-table-row-shadow-floating-2-offset-y": "var(--ctr-shadow-large-offset-y)",
    // "--ctr-data-table-row-shadow-floating-2-spread": "var(--ctr-shadow-large-spread)",
    '--ctr-editor-background-color-disabled': colors.background,
    '--ctr-editor-background-color': colors.surface,
    '--ctr-editor-border-color-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-editor-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-editor-border-color': colors.backgroundDim,
    // "--ctr-editor-border-width-focused": "var(--sjs-stroke-x2)",
    // "--ctr-editor-border-width": "var(--sjs-stroke-x1)",
    '--ctr-editor-button-background-color-hovered': colors.background,
    // "--ctr-editor-button-corner-radius": "var(--sjs-corner-radius-x05)",
    '--ctr-editor-button-icon-color-disabled': colors.iconColor,
    '--ctr-editor-button-icon-color': colors.iconColor,
    // "--ctr-editor-button-icon-height": "var(--sjs-size-x3)",
    // "--ctr-editor-button-icon-opacity-disabled": 0.25,
    // "--ctr-editor-button-icon-opacity-pressed": 0.5,
    // "--ctr-editor-button-icon-width": "var(--sjs-size-x3)",
    // "--ctr-editor-button-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-editor-button-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-editor-button-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-editor-button-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-editor-button-text-color': colors.textColor,
    // "--ctr-editor-buttons-gap": "var(--sjs-spacing-x05)",
    '--ctr-editor-color-swatch-icon-height': 'var(--sjs-size-x2)',
    '--ctr-editor-color-swatch-icon-width': 'var(--sjs-size-x2)',
    '--ctr-editor-color-swatch-margin-left': 'var(--sjs-spacing-x150)',
    '--ctr-editor-content-icon-color': colors.iconColor,
    // "--ctr-editor-content-margin-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-editor-content-margin-left": "var(--sjs-spacing-x150)",
    // "--ctr-editor-content-margin-right": "var(--sjs-spacing-x150)",
    // "--ctr-editor-content-margin-top": "var(--sjs-spacing-x1)",
    '--ctr-editor-content-text-color-disabled': colors.textColor,
    '--ctr-editor-content-text-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-editor-content-text-color': colors.textColor,
    // "--ctr-editor-content-text-opacity-disabled": 0.25,
    // "--ctr-editor-corner-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-editor-gap": "var(--sjs-spacing-x05)",
    '--ctr-editor-label-color-disabled': colors.textColor,
    '--ctr-editor-label-color': colors.inputPlaceholderColor,
    // "--ctr-editor-label-opacity-disabled": 0.25,
    // "--ctr-editor-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-editor-padding-left": "var(--sjs-spacing-x05)",
    // "--ctr-editor-padding-right": "var(--sjs-spacing-x05)",
    // "--ctr-editor-padding-top": "var(--sjs-spacing-x05)",
    '--ctr-error-message-background-color': 'var(--sjs-semantic-red-background-10)',
    // "--ctr-error-message-corner-radius": "var(--sjs-corner-radius-x05)",
    // "--ctr-error-message-gap": "var(--sjs-spacing-x1)",
    '--ctr-error-message-icon-color': 'var(--sjs-semantic-red-background-500)',
    // "--ctr-error-message-icon-height": "var(--sjs-size-x3)",
    // "--ctr-error-message-icon-width": "var(--sjs-size-x3)",
    // "--ctr-error-message-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-error-message-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-error-message-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-error-message-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-error-message-text-color': colors.textColor,
    '--ctr-expression-item-background-color-action-hovered': 'var(--sjs-semantic-red-background-500)',
    '--ctr-expression-item-background-color-action': 'var(--sjs-semantic-red-background-10)',
    '--ctr-expression-item-background-color-button-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-expression-item-background-color-button': colors.backgroundDim,
    '--ctr-expression-item-background-color-conjunction-hovered': 'var(--sjs-semantic-yellow-background-500)',
    '--ctr-expression-item-background-color-conjunction': 'var(--sjs-semantic-yellow-background-10)',
    '--ctr-expression-item-background-color-operator-hovered': 'var(--sjs-semantic-yellow-background-500)',
    '--ctr-expression-item-background-color-operator': 'var(--sjs-semantic-yellow-background-10)',
    '--ctr-expression-item-background-color-parameter-error': colors.background,
    '--ctr-expression-item-background-color-parameter-hovered': 'var(--sjs-semantic-blue-background-500)',
    '--ctr-expression-item-background-color-parameter': 'var(--sjs-semantic-blue-background-10)',
    // "--ctr-expression-item-corner-radius": "var(--sjs-corner-radius-x1)",
    // "--ctr-expression-item-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-expression-item-padding-left-button": "var(--sjs-spacing-x4)",
    // "--ctr-expression-item-padding-left": "var(--sjs-spacing-x2)",
    // "--ctr-expression-item-padding-right-button": "var(--sjs-spacing-x4)",
    // "--ctr-expression-item-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-expression-item-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-expression-item-text-color-action-hovered': 'var(--sjs-semantic-red-foreground-100)',
    '--ctr-expression-item-text-color-action': colors.textColor,
    '--ctr-expression-item-text-color-button-hovered': 'var(--sjs-primary-foreground-100)',
    '--ctr-expression-item-text-color-button': 'var(--sjs-primary-background-500)',
    '--ctr-expression-item-text-color-conjunction-hovered': 'var(--sjs-semantic-yellow-foreground-100)',
    '--ctr-expression-item-text-color-conjunction': colors.textColor,
    '--ctr-expression-item-text-color-function': colors.textColor,
    '--ctr-expression-item-text-color-operator-empty': colors.inputPlaceholderColor,
    '--ctr-expression-item-text-color-operator-hovered': 'var(--sjs-semantic-yellow-foreground-100)',
    '--ctr-expression-item-text-color-operator': colors.textColor,
    '--ctr-expression-item-text-color-parameter-empty': colors.inputPlaceholderColor,
    '--ctr-expression-item-text-color-parameter-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-expression-item-text-color-parameter-hovered': 'var(--sjs-semantic-blue-foreground-100)',
    '--ctr-expression-item-text-color-parameter': colors.textColor,
    // "--ctr-expression-rows-gap": "var(--sjs-spacing-x2)",
    // "--ctr-font-code-line-height": "var(--sjs-line-height-x3)",
    // "--ctr-font-code-size": "var(--sjs-font-size-x2)",
    // "--ctr-font-default-line-height-all-caps": "var(--sjs-line-height-x2)",
    // "--ctr-font-default-line-height": "var(--sjs-line-height-x3)",
    // "--ctr-font-default-size": "var(--sjs-font-size-x2)",
    // "--ctr-font-large-line-height": "var(--sjs-line-height-x5)",
    // "--ctr-font-large-size": "var(--sjs-font-size-x4)",
    // "--ctr-font-medium-line-height": "var(--sjs-line-height-x4)",
    // "--ctr-font-medium-size": "var(--sjs-font-size-x3)",
    // "--ctr-font-small-line-height": "var(--sjs-line-height-x2)",
    // "--ctr-font-small-size": "var(--sjs-font-size-x150)",
    // "--ctr-font-unit": "8px",
    // "--ctr-image-gallery-item-corner-radius": "var(--sjs-corner-radius-x075)"
    '--ctr-font-family-code': 'var(--font-outfit)',
    '--ctr-font-family': 'var(--font-outfit)',
    '--sjs-default-font-family': 'var(--font-outfit)',
    '--sjs-font-family': 'var(--font-outfit)',
    '--ctr-image-gallery-item-title-color': colors.textColor,
    // "--ctr-label-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-label-padding-left": "0px",
    // "--ctr-label-padding-right": "0px",
    // "--ctr-label-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-label-text-color-disabled': colors.textColor,
    '--ctr-label-text-color': colors.textColor,
    // "--ctr-line-height-unit": "8px",
    '--ctr-list-item-background-color-hovered': colors.backgroundDim,
    '--ctr-list-item-background-color-selected-submenu': colors.backgroundDim,
    '--ctr-list-item-background-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-color-swatch-corner-radius': 'var(--sjs-corner-radius-x05)',
    '--ctr-list-item-color-swatch-height': 'var(--sjs-spacing-x3)',
    '--ctr-list-item-color-swatch-width': 'var(--sjs-spacing-x4)',
    '--ctr-list-item-contextual-buttons-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-list-item-corner-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-list-item-gap": "var(--sjs-spacing-x2)",
    '--ctr-list-item-icon-color-disabled': colors.textColor,
    '--ctr-list-item-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-icon-color-selected-submenu': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-icon-color-selected': 'var(--sjs-primary-foreground-100)',
    '--ctr-list-item-icon-color': 'var(--sjs-primary-background-500)',
    '--ctr-list-item-label-icon-color-disabled': colors.textColor,
    '--ctr-list-item-label-icon-color-hovered': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-list-item-padding-bottom-with-icon": "var(--sjs-spacing-x150)",
    // "--ctr-list-item-padding-left": "var(--sjs-spacing-x2)",
    // "--ctr-list-item-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-list-item-padding-top-with-icon": "var(--sjs-spacing-x150)",
    '--ctr-list-item-submenu-arrow-color-hovered-item': colors.textColor,
    '--ctr-list-item-submenu-arrow-color-selected-item-submenu': colors.textColor,
    '--ctr-list-item-submenu-arrow-color': colors.textColor,
    '--ctr-list-item-text-color-hovered': colors.textColor,
    '--ctr-list-item-text-color-selected-submenu': colors.textColor,
    '--ctr-list-item-text-color-selected': 'var(--sjs-primary-foreground-100)',
    '--ctr-list-item-text-color': colors.textColor,
    // "--ctr-list-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-list-padding-right": "var(--sjs-spacing-x1)",
    '--ctr-list-search-border-color': colors.borderColor,
    '--ctr-list-search-icon-color': colors.textColor,
    // "--ctr-list-search-padding-left": "var(--sjs-spacing-x3)",
    '--ctr-list-search-text-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-menu-border-color': colors.borderColor,
    '--ctr-menu-item-background-color-hovered': colors.backgroundDim,
    '--ctr-menu-item-background-color': colors.background,
    '--ctr-menu-item-border-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-item-icon-color': colors.textColor,
    // "--ctr-menu-item-icon-height": "var(--sjs-size-x3)",
    // "--ctr-menu-item-icon-width": "var(--sjs-size-x3)",
    // "--ctr-menu-item-opacity-disabled": 0.25,
    // "--ctr-menu-item-padding-bottom": "var(--sjs-spacing-x250)",
    // "--ctr-menu-item-padding-left-icon": "var(--sjs-spacing-x2)",
    // "--ctr-menu-item-padding-left": "var(--sjs-spacing-x3)",
    // "--ctr-menu-item-padding-right-icon": "var(--sjs-spacing-x2)",
    // "--ctr-menu-item-padding-right": "var(--sjs-spacing-x3)",
    // "--ctr-menu-item-padding-top": "var(--sjs-spacing-x250)",
    '--ctr-menu-item-text-color': colors.textColor,
    '--ctr-menu-toolbar-button-background-color-hovered': colors.backgroundDim,
    '--ctr-menu-toolbar-button-background-color-pressed': colors.backgroundDim,
    '--ctr-menu-toolbar-button-background-color-selected': colors.backgroundDim,
    // "--ctr-menu-toolbar-button-corner-radius": "var(--sjs-corner-radius-x1)",
    // "--ctr-menu-toolbar-button-gap": "var(--sjs-spacing-x1)",
    '--ctr-menu-toolbar-button-icon-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-toolbar-button-icon-color': colors.textColor,
    // "--ctr-menu-toolbar-button-icon-height": "var(--sjs-size-x3)",
    // "--ctr-menu-toolbar-button-icon-width": "var(--sjs-size-x3)",
    // "--ctr-menu-toolbar-button-opacity-disabled": 0.25,
    // "--ctr-menu-toolbar-button-opacity-pressed": 0.5,
    // "--ctr-menu-toolbar-button-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-menu-toolbar-button-padding-left-with-description": "var(--sjs-spacing-x150)",
    // "--ctr-menu-toolbar-button-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-menu-toolbar-button-padding-right-with-description": "var(--sjs-spacing-x150)",
    // "--ctr-menu-toolbar-button-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-menu-toolbar-button-padding-top-with-description": "var(--sjs-spacing-x05)",
    // "--ctr-menu-toolbar-button-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-menu-toolbar-button-text-color-secondary': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-menu-toolbar-button-text-color-selected': 'var(--sjs-primary-background-500)',
    '--ctr-menu-toolbar-button-text-color': colors.textColor,
    // "--ctr-menu-toolbar-gap": "var(--sjs-spacing-x2)",
    // "--ctr-menu-toolbar-padding-horizontal": "var(--sjs-spacing-x2)",
    // "--ctr-menu-toolbar-padding-vertical": "var(--sjs-spacing-x150)",
    '--ctr-notification-background-color-error': 'var(--sjs-semantic-red-background-500)',
    '--ctr-notification-background-color': colors.background,
    // "--ctr-notification-opacity-error": 1,
    // "--ctr-notification-opacity": 0.75,
    '--ctr-notification-text-color-error': 'var(--sjs-semantic-red-foreground-100)',
    '--ctr-notification-text-color': colors.textColor,
    '--ctr-page-banner-background-color': 'var(--sjs-secondary-background-500)',
    '--ctr-page-banner-text-color': 'var(--sjs-secondary-foreground-100)',
    '--ctr-page-navigator-button-background-color-hovered': colors.backgroundDim,
    '--ctr-page-navigator-button-background-color-pressed': colors.backgroundDim,
    // "--ctr-page-navigator-button-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-page-navigator-button-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-page-navigator-button-icon-color': colors.iconColor,
    // "--ctr-page-navigator-button-icon-height": "var(--sjs-size-x3)",
    // "--ctr-page-navigator-button-icon-width": "var(--sjs-size-x3)",
    // "--ctr-page-navigator-button-opacity-pressed": 0.5,
    // "--ctr-page-navigator-button-padding": "var(--sjs-spacing-x125)",
    '--ctr-page-navigator-item-background-color-hovered': colors.background,
    // "--ctr-page-navigator-item-corner-radius": "var(--sjs-corner-radius-x075)",
    '--ctr-page-navigator-item-dot-border-color-selected': colors.iconColor,
    '--ctr-page-navigator-item-dot-color-default': colors.iconColor,
    '--ctr-page-navigator-item-dot-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-page-navigator-item-dot-color-selected': 'var(--sjs-special-background)',
    // "--ctr-page-navigator-item-dot-radius-large": "var(--sjs-size-x1)",
    // "--ctr-page-navigator-item-dot-radius-small": "var(--sjs-size-x075)",
    // "--ctr-page-navigator-item-gap": "var(--sjs-spacing-x1)",
    // "--ctr-page-navigator-item-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-page-navigator-item-padding-left-hovered": "var(--sjs-spacing-x2)",
    // "--ctr-page-navigator-item-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-page-navigator-item-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-page-navigator-item-text-color-hovered': colors.textColor,
    // "--ctr-page-navigator-padding-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-page-navigator-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-page-navigator-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-page-navigator-padding-top": "var(--sjs-spacing-x150)",
    '--ctr-popup-background-color': colors.background,
    // "--ctr-popup-buttons-gap": "var(--sjs-spacing-x2)",
    // "--ctr-popup-corner-radius": "var(--sjs-corner-radius-x2)",
    '--ctr-popup-description-color': colors.textColor,
    // "--ctr-popup-gap": "var(--sjs-spacing-x4)",
    '--ctr-popup-haze-background-color': 'var(--sjs-special-haze)',
    '--ctr-popup-menu-background-color': colors.background,
    // "--ctr-popup-menu-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-popup-menu-footer-background-color': colors.background,
    '--ctr-popup-menu-footer-border-color': colors.borderColor,
    // "--ctr-popup-menu-footer-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-popup-menu-footer-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-popup-menu-footer-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-popup-menu-footer-padding-top": "var(--sjs-spacing-x05)",
    '--ctr-popup-menu-pointer-color': colors.background,
    '--ctr-popup-message-color': colors.textColor,
    // "--ctr-popup-padding-bottom": "var(--sjs-spacing-x4)",
    // "--ctr-popup-padding-left": "var(--sjs-spacing-x4)",
    // "--ctr-popup-padding-right": "var(--sjs-spacing-x4)",
    // "--ctr-popup-padding-top": "var(--sjs-spacing-x4)",
    // "--ctr-popup-shadow-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-popup-shadow-1-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-popup-shadow-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-popup-shadow-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-popup-shadow-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-popup-shadow-2-blur": "var(--ctr-shadow-large-blur)",
    '--ctr-popup-shadow-2-color': 'var(--ctr-shadow-large-color)',
    // "--ctr-popup-shadow-2-offset-x": "var(--ctr-shadow-large-offset-x)",
    // "--ctr-popup-shadow-2-offset-y": "var(--ctr-shadow-large-offset-y)",
    // "--ctr-popup-shadow-2-spread": "var(--ctr-shadow-large-spread)",
    // "--ctr-popup-shadow-3-blur": "var(--ctr-shadow-x-large-blur)",
    '--ctr-popup-shadow-3-color': 'var(--ctr-shadow-x-large-color)',
    // "--ctr-popup-shadow-3-offset-x": "var(--ctr-shadow-x-large-offset-x)",
    // "--ctr-popup-shadow-3-offset-y": "var(--ctr-shadow-x-large-offset-y)",
    // "--ctr-popup-shadow-3-spread": "var(--ctr-shadow-x-large-spread)",
    '--ctr-popup-title-color': colors.textColor,
    '--ctr-preview-pager-background-color': colors.background,
    '--ctr-preview-pager-border-color': colors.borderColor,
    '--ctr-property-grid-background-color': colors.background,
    '--ctr-property-grid-border-color': colors.borderColor, // here
    '--ctr-property-grid-chapter-caption-background-color-focused': colors.backgroundDim,
    '--ctr-property-grid-chapter-caption-background-color-hovered': colors.backgroundDim,
    '--ctr-property-grid-chapter-caption-background-color': colors.background,
    '--ctr-property-grid-chapter-caption-border-color': colors.borderColor,
    '--ctr-property-grid-chapter-caption-text-color-disabled': colors.textColor,
    '--ctr-property-grid-chapter-caption-text-color-selected': colors.textColor,
    '--ctr-property-grid-chapter-caption-text-color': colors.textColor,
    '--ctr-property-grid-form-background-color': colors.background,
    // "--ctr-property-grid-form-border-width-bottom": "0px",
    '--ctr-property-grid-group-caption-text-color': colors.textColor,
    '--ctr-property-grid-header-background-color': colors.background,
    '--ctr-property-grid-header-border-color': 'var(--sjs-primary-background-500)',
    // "--ctr-property-grid-header-border-width-bottom": "var(--sjs-stroke-x2)",
    // "--ctr-property-grid-header-padding-bottom-with-subtitle": "var(--sjs-spacing-x075)",
    // "--ctr-property-grid-header-padding-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-header-padding-left": "var(--sjs-spacing-x2)",
    // "--ctr-property-grid-header-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-property-grid-header-padding-top-with-subtitle": "var(--sjs-spacing-x075)",
    // "--ctr-property-grid-header-padding-top": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-placeholder-image-margin-top": "var(--sjs-spacing-x3)",
    // "--ctr-property-grid-placeholder-padding-bottom": "0px",
    // "--ctr-property-grid-placeholder-padding-left": "var(--sjs-spacing-x6)",
    // "--ctr-property-grid-placeholder-padding-right": "var(--sjs-spacing-x6)",
    // "--ctr-property-grid-placeholder-padding-top": "var(--sjs-spacing-x12)",
    '--ctr-property-grid-placeholder-text-description-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-property-grid-placeholder-text-gap": "var(--sjs-spacing-x1)",
    // "--ctr-property-grid-placeholder-text-max-width": "320px",
    '--ctr-property-grid-placeholder-text-title-color': colors.textColor,
    '--ctr-property-grid-search-background-color': colors.background,
    '--ctr-property-grid-search-border-color': colors.backgroundDim,
    '--ctr-property-grid-search-button-background-color-hovered': colors.background,
    '--ctr-property-grid-search-button-icon-color': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-count-text-color': colors.inputPlaceholderColor,
    // "--ctr-property-grid-search-gap": "var(--sjs-spacing-x1)",
    '--ctr-property-grid-search-icon-color': colors.inputPlaceholderColor,
    // "--ctr-property-grid-search-icon-height": "var(--sjs-size-x3)",
    // "--ctr-property-grid-search-icon-width": "var(--sjs-size-x3)",
    // "--ctr-property-grid-search-padding-bottom": "var(--sjs-spacing-x2)",
    // "--ctr-property-grid-search-padding-left": "var(--sjs-spacing-x2)",
    // "--ctr-property-grid-search-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-property-grid-search-padding-top": "var(--sjs-spacing-x2)",
    '--ctr-property-grid-search-text-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-property-grid-search-text-color': colors.textColor,
    '--ctr-property-grid-switcher-text-color': colors.textColor,
    '--ctr-property-grid-tabs-background-color': colors.background,
    '--ctr-property-grid-tabs-border-color': colors.borderColor,
    // "--ctr-property-grid-tabs-border-width": "var(--sjs-stroke-x1)",
    // "--ctr-property-grid-tabs-gap": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-tabs-padding-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-tabs-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-tabs-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-tabs-padding-top": "var(--sjs-spacing-x150)",
    // "--ctr-property-grid-tabs-separator-margin": "var(--sjs-spacing-x150)",
    '--ctr-radio-button-background-color-disabled': colors.background,
    '--ctr-radio-button-background-color-hovered': colors.background,
    '--ctr-radio-button-background-color-selected-hovered': colors.background,
    '--ctr-radio-button-background-color': colors.background,
    '--ctr-radio-button-border-color-disabled': colors.backgroundDim,
    '--ctr-radio-button-border-color': colors.backgroundDim,
    '--ctr-radio-button-text-color-disabled': colors.textColor,
    '--ctr-radio-button-text-color': colors.textColor,
    '--ctr-scrollbar-background-color': colors.backgroundDim,
    // "--ctr-scrollbar-padding-vertical-hovered": "var(--sjs-spacing-x025)",
    // "--ctr-scrollbar-padding-vertical": "var(--sjs-spacing-x05)",
    // "--ctr-scrollbar-width": "var(--sjs-size-x150)",
    '--ctr-search-button-background-color-hovered': colors.backgroundDim,
    // "--ctr-search-button-corner-radius": "var(--sjs-corner-radius-x05)",
    // "--ctr-search-button-icon-height": "var(--sjs-size-x2)",
    // "--ctr-search-button-icon-width": "var(--sjs-size-x2)",
    // "--ctr-search-button-padding-horizontal": "var(--sjs-spacing-x05)",
    // "--ctr-search-button-padding-vertical": "var(--sjs-spacing-x05)",
    '--ctr-search-icon-color': colors.textColor,
    // "--ctr-search-toolbar-gap": "var(--sjs-spacing-x05)",
    '--ctr-separator-color': colors.borderColor,
    // "--ctr-separator-width": "var(--sjs-size-x0125)",
    // "--ctr-shadow-large-blur": "32px",
    '--ctr-shadow-large-color': 'var(--sjs-special-glow)',
    // "--ctr-shadow-large-offset-x": "0px",
    // "--ctr-shadow-large-offset-y": "16px",
    // "--ctr-shadow-large-spread": "0px",
    // "--ctr-shadow-medium-blur": "8px",
    '--ctr-shadow-medium-color': 'var(--sjs-special-glow)',
    // "--ctr-shadow-medium-offset-x": "0px",
    // "--ctr-shadow-medium-offset-y": "2px",
    // "--ctr-shadow-medium-spread": "0px",
    // "--ctr-shadow-small-blur": "2px",
    '--ctr-shadow-small-color': 'var(--sjs-special-shadow)',
    // "--ctr-shadow-small-offset-x": "0px",
    // "--ctr-shadow-small-offset-y": "1px",
    // "--ctr-shadow-small-spread": "0px",
    // "--ctr-shadow-x-large-blur": "64px",
    '--ctr-shadow-x-large-color': 'var(--sjs-special-glow)',
    // "--ctr-shadow-x-large-offset-x": "0px",
    // "--ctr-shadow-x-large-offset-y": "32px",
    // "--ctr-shadow-x-large-spread": "0px",
    // "--ctr-size-unit": "8px",
    // "--ctr-spacing-unit": "8px",
    '--ctr-string-table-group-header-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-string-table-group-header-text-color': 'var(--sjs-layer-2-foreground-75)',
    '--ctr-string-table-header-background-color': colors.background,
    '--ctr-string-table-header-text-color': colors.iconColor,
    '--ctr-string-table-row-background-color': colors.background,
    '--ctr-string-table-row-border-color': colors.backgroundDim,
    '--ctr-string-table-row-expand-button-icon-color-default': colors.textColor,
    // "--ctr-string-table-row-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-string-table-row-padding-left": "var(--sjs-spacing-x3)",
    // "--ctr-string-table-row-padding-right": "var(--sjs-spacing-x3)",
    // "--ctr-string-table-row-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-string-table-row-text-color-title': colors.textColor,
    // "--ctr-stroke-unit": "1px",
    // "--ctr-super-tooltip-corder-radius": "var(--sjs-corner-radius-x075)",
    '--ctr-surface-background-color': colors.surface,
    // "--ctr-surface-placeholder-max-width": "var(--sjs-size-x90)",
    // "--ctr-surface-placeholder-padding-bottom": "var(--sjs-spacing-x16)",
    // "--ctr-surface-placeholder-padding-left": "var(--sjs-spacing-x6)",
    // "--ctr-surface-placeholder-padding-right": "var(--sjs-spacing-x6)",
    // "--ctr-surface-placeholder-padding-top": "0px",
    '--ctr-surface-placeholder-text-description-color': colors.textColorDim,
    // "--ctr-surface-placeholder-text-gap": "var(--sjs-spacing-x1)",
    // "--ctr-surface-placeholder-text-margin-bottom": "var(--sjs-spacing-x6)",
    // "--ctr-surface-placeholder-text-margin-top": "var(--sjs-spacing-x4)",
    '--ctr-surface-placeholder-text-title-color': colors.textColor,
    // "--ctr-surface-toolbar-gap": "var(--sjs-spacing-x1)",
    // "--ctr-surface-toolbar-padding-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-surface-toolbar-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-surface-toolbar-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-surface-toolbar-padding-top": "var(--sjs-spacing-x150)",
    '--ctr-survey-action-button-background-color-hovered-negative': 'var(--sjs-semantic-red-background-10)',
    '--ctr-survey-action-button-background-color-hovered-positive': colors.backgroundDim,
    // "--ctr-survey-action-button-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-survey-action-button-icon-color-disabled': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-action-button-icon-color-negative': 'var(--sjs-semantic-red-background-500)',
    '--ctr-survey-action-button-icon-color-positive': 'var(--sjs-primary-background-500)',
    // "--ctr-survey-action-button-opacity-disabled": 0.25,
    '--ctr-survey-action-button-text-color-disabled': colors.textColor,
    '--ctr-survey-action-button-text-color-positive': 'var(--sjs-primary-background-500)',
    // "--ctr-survey-checkboxes-item-corner-radius-floating": "var(--sjs-corner-radius-x1)",
    // "--ctr-survey-contextual-button-height": "var(--sjs-size-x6)",
    // "--ctr-survey-contextual-button-padding-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-survey-contextual-button-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-survey-contextual-button-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-survey-contextual-button-padding-top": "var(--sjs-spacing-x150)",
    // "--ctr-survey-contextual-button-width": "var(--sjs-size-x6)",
    '--ctr-survey-drop-indicator-color': 'var(--sjs-primary-background-500)',
    '--ctr-survey-header-logo-placeholder-background-color-hovered': colors.backgroundDim,
    // "--ctr-survey-header-logo-placeholder-corner-radius": "var(--sjs-corner-radius-round)",
    '--ctr-survey-header-logo-placeholder-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-survey-header-logo-placeholder-icon-color': colors.inputPlaceholderColor,
    // "--ctr-survey-header-logo-placeholder-icon-height": "var(--sjs-size-x6)",
    // "--ctr-survey-header-logo-placeholder-icon-opacity": 0.5,
    // "--ctr-survey-header-logo-placeholder-icon-width": "var(--sjs-size-x6)",
    '--ctr-survey-header-text-description-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-header-text-title-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-image-picker-drop-spot-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-survey-info-panel-background-color': 'var(--sjs-layer-2-background-500)',
    '--ctr-survey-info-panel-text-color': 'var(--sjs-layer-2-foreground-50)',
    '--ctr-survey-item-actionbar-drag-indicator-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-survey-item-actionbar-drag-indicator-height": "var(--sjs-size-x3)",
    // "--ctr-survey-item-actionbar-drag-indicator-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-survey-item-actionbar-drag-indicator-padding-left": "var(--sjs-spacing-x1)",
    // "--ctr-survey-item-actionbar-drag-indicator-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-survey-item-actionbar-drag-indicator-padding-top": "var(--sjs-spacing-x05)",
    // "--ctr-survey-item-actionbar-drag-indicator-width": "var(--sjs-size-x3)",
    // "--ctr-survey-matching-item-corner-radius-floating": "var(--sjs-corner-radius-x2)",
    // "--ctr-survey-matching-item-padding-bottom-floating": "var(--sjs-spacing-x1)",
    // "--ctr-survey-matching-item-padding-right-floating": "var(--sjs-spacing-x1)",
    // "--ctr-survey-matching-item-padding-top-floating": "var(--sjs-spacing-x1)",
    '--ctr-survey-page-background-color-hovered': colors.background,
    '--ctr-survey-page-background-color-selected': colors.background,
    '--ctr-survey-page-border-color-hovered': 'var(--sjs-secondary-background-25)',
    '--ctr-survey-page-border-color-selected': 'var(--sjs-secondary-background-500)',
    // "--ctr-survey-page-border-width-hovered": "var(--sjs-stroke-x2)",
    // "--ctr-survey-page-border-width-selected": "var(--sjs-stroke-x2)",
    // "--ctr-survey-page-drag-indicator-height": "var(--sjs-size-x2)",
    // "--ctr-survey-page-drag-indicator-opacity": 0.5,
    // "--ctr-survey-page-drag-indicator-width": "var(--sjs-size-x3)",
    '--ctr-survey-page-header-title-color-placeholder': colors.inputPlaceholderColor,
    '--ctr-survey-page-placeholder-text-color': colors.inputPlaceholderColor,
    '--ctr-survey-page-toolbar-item-background-color-hovered': colors.backgroundDim,
    '--ctr-survey-page-toolbar-item-background-color-selected': colors.backgroundDim,
    // "--ctr-survey-page-toolbar-item-corner-radius": "var(--sjs-corner-radius-x075)",
    '--ctr-survey-page-toolbar-item-icon-color-pressed': colors.inputPlaceholderColor,
    '--ctr-survey-page-toolbar-item-text-color': colors.textColor,
    '--ctr-survey-placeholder-border-color': colors.borderColor,
    // "--ctr-survey-placeholder-gap": "var(--sjs-spacing-x05)",
    // "--ctr-survey-placeholder-padding-bottom-with-button": "var(--sjs-spacing-x6)",
    // "--ctr-survey-placeholder-padding-left": "var(--sjs-spacing-x8)",
    // "--ctr-survey-placeholder-padding-right": "var(--sjs-spacing-x8)",
    // "--ctr-survey-placeholder-padding-top-with-button": "var(--sjs-spacing-x8)",
    '--ctr-survey-placeholder-text-color': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-survey-question-panel-border-color-hovered': 'var(--sjs-secondary-background-25)',
    '--ctr-survey-question-panel-border-color-selected': 'var(--sjs-secondary-background-500)',
    // "--ctr-survey-question-panel-border-width-hovered": "var(--sjs-stroke-x2)",
    // "--ctr-survey-question-panel-border-width-selected": "var(--sjs-stroke-x2)",
    '--ctr-survey-question-panel-drag-area-drag-indicator-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-survey-question-panel-drag-area-drag-indicator-height": "var(--sjs-size-x2)",
    // "--ctr-survey-question-panel-drag-area-drag-indicator-opacity": 0.5,
    // "--ctr-survey-question-panel-drag-area-drag-indicator-width": "var(--sjs-size-x3)",
    // "--ctr-survey-question-panel-floating-toolbar-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-survey-question-panel-floating-toolbar-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-survey-question-panel-toolbar-gap": "var(--sjs-spacing-x1)",
    '--ctr-survey-question-panel-toolbar-item-background-color-hovered': colors.backgroundDim,
    '--ctr-survey-question-panel-toolbar-item-background-color-selected': 'var(--sjs-secondary-background-10)',
    // "--ctr-survey-question-panel-toolbar-item-corner-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-survey-question-panel-toolbar-item-gap": "var(--sjs-spacing-x05)",
    '--ctr-survey-question-panel-toolbar-item-icon-color': 'var(--sjs-secondary-background-500)', //xxxx
    // "--ctr-survey-question-panel-toolbar-item-icon-container-height": "var(--sjs-size-x3)",
    // "--ctr-survey-question-panel-toolbar-item-icon-container-width": "var(--sjs-size-x3)",
    // "--ctr-survey-question-panel-toolbar-item-icon-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-icon-padding-left": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-icon-padding-right": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-icon-padding-top": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-opacity-disabled": 0.25,
    // "--ctr-survey-question-panel-toolbar-item-opacity-muted": 0.5,
    // "--ctr-survey-question-panel-toolbar-item-opacity-pressed": 0.5,
    // "--ctr-survey-question-panel-toolbar-item-padding-bottom-small": "0px",
    // "--ctr-survey-question-panel-toolbar-item-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-padding-left-small": "0px",
    // "--ctr-survey-question-panel-toolbar-item-padding-left": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-padding-right-small": "0px",
    // "--ctr-survey-question-panel-toolbar-item-padding-right-with-text": "var(--sjs-spacing-x1)",
    // "--ctr-survey-question-panel-toolbar-item-padding-right": "var(--sjs-spacing-x05)",
    // "--ctr-survey-question-panel-toolbar-item-padding-top-small": "0px",
    // "--ctr-survey-question-panel-toolbar-item-padding-top": "var(--sjs-spacing-x05)",
    '--ctr-survey-question-panel-toolbar-item-text-color': colors.textColor,
    '--ctr-survey-radio-button-group-item-background-color-floating': colors.background,
    // "--ctr-survey-radio-button-group-item-corner-radius-floating": "var(--sjs-corner-radius-x1)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-1-blur": "var(--ctr-shadow-large-blur)",
    '--ctr-survey-radio-button-group-item-shadow-floating-1-color': 'var(--ctr-shadow-large-color)',
    // "--ctr-survey-radio-button-group-item-shadow-floating-1-offset-x": "var(--ctr-shadow-large-offset-x)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-1-offset-y": "var(--ctr-shadow-large-offset-y)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-1-spread": "var(--ctr-shadow-large-spread)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-2-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-survey-radio-button-group-item-shadow-floating-2-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-survey-radio-button-group-item-shadow-floating-2-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-2-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-survey-radio-button-group-item-shadow-floating-2-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-survey-ranking-item-corner-radius-floating": "var(--sjs-corner-radius-x1)",
    // "--ctr-survey-resize-frame-grip-height": "var(--sjs-size-x150)",
    // "--ctr-survey-resize-frame-grip-width": "var(--sjs-size-x150)",
    // "--ctr-survey-resize-frame-margin": "var(--sjs-spacing-x1n)",
    '--ctr-text-decor-text-color-code': colors.textColor,
    '--ctr-toggle-button-background-color-checked-focused': 'var(--sjs-primary-foreground-100)',
    '--ctr-toggle-button-background-color-checked': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-background-color-hovered': colors.background,
    '--ctr-toggle-button-background-color': colors.background,
    '--ctr-toggle-button-border-color-focused': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-border-color': colors.backgroundDim,
    // "--ctr-toggle-button-corner-radius": "var(--sjs-corner-radius-round)",
    // "--ctr-toggle-button-gap-label": "var(--sjs-spacing-x1)",
    // "--ctr-toggle-button-gap": "var(--sjs-spacing-x05)",
    '--ctr-toggle-button-label-text-color': colors.textColor,
    // "--ctr-toggle-button-padding-bottom": "var(--sjs-spacing-x075)",
    // "--ctr-toggle-button-padding-left": "var(--sjs-spacing-x075)",
    // "--ctr-toggle-button-padding-right": "var(--sjs-spacing-x075)",
    // "--ctr-toggle-button-padding-top": "var(--sjs-spacing-x075)",
    '--ctr-toggle-button-thumb-background-color-active': colors.iconColor,
    '--ctr-toggle-button-thumb-background-color-checked-focused': 'var(--sjs-primary-background-500)',
    '--ctr-toggle-button-thumb-background-color-checked': 'var(--sjs-primary-foreground-100)',
    '--ctr-toggle-button-thumb-border-color': colors.backgroundDim,
    // "--ctr-toggle-button-thumb-border-width": "0px",
    // "--ctr-toggle-button-thumb-corner-radius": "var(--sjs-corner-radius-round)",
    // "--ctr-toggle-button-thumb-height": "var(--sjs-size-x150)",
    // "--ctr-toggle-button-thumb-width": "var(--sjs-size-x150)",
    '--ctr-toolbox-background-color': colors.surface,
    '--ctr-toolbox-border-color': colors.borderColor,
    // "--ctr-toolbox-border-width-right": "var(--sjs-stroke-x1)",
    '--ctr-toolbox-button-background-color-hovered': colors.backgroundDim,
    // "--ctr-toolbox-gap": "var(--sjs-spacing-x05)",
    // "--ctr-toolbox-group-gap": "var(--sjs-spacing-x05)",
    '--ctr-toolbox-group-header-border-color': colors.borderColor,
    // "--ctr-toolbox-group-header-border-width-bottom": "var(--sjs-stroke-x1)",
    // "--ctr-toolbox-group-header-border-width-left": "0px",
    // "--ctr-toolbox-group-header-border-width-right": "0px",
    // "--ctr-toolbox-group-header-border-width-top": "0px",
    '--ctr-toolbox-group-header-expand-button-color': colors.textColor,
    // "--ctr-toolbox-group-header-margin-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-group-header-margin-left": "0px",
    // "--ctr-toolbox-group-header-margin-right": "0px",
    // "--ctr-toolbox-group-header-margin-top": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-group-header-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-group-header-padding-left": "var(--sjs-spacing-x3)",
    // "--ctr-toolbox-group-header-padding-right": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-group-header-padding-top": "var(--sjs-spacing-x1)",
    '--ctr-toolbox-group-header-text-color': colors.textColor,
    // "--ctr-toolbox-group-padding-left-compact": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-group-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-group-padding-right-compact": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-group-padding-right": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-item-align": "stretch",
    '--ctr-toolbox-item-background-color-hovered': colors.backgroundDim,
    '--ctr-toolbox-item-background-color-pressed': colors.backgroundDim,
    '--ctr-toolbox-item-background-color-submenu': colors.background,
    // "--ctr-toolbox-item-banner-beak-display": "block",
    // "--ctr-toolbox-item-banner-icon-display": "none",
    '--ctr-toolbox-item-border-color-floating': 'var(--sjs-secondary-background-500)',
    // "--ctr-toolbox-item-corner-radius": "var(--sjs-corner-radius-x1)",
    '--ctr-toolbox-item-icon-color-disabled': colors.textColor,
    '--ctr-toolbox-item-icon-color-hovered': 'var(--sjs-primary-background-500)',
    '--ctr-toolbox-item-icon-color-pressed': colors.textColor,
    '--ctr-toolbox-item-icon-color': colors.iconColor,
    // "--ctr-toolbox-item-icon-height": "var(--sjs-size-x3)",
    // "--ctr-toolbox-item-icon-opacity-disabled": 0.25,
    // "--ctr-toolbox-item-icon-opacity-pressed": 0.35,
    // "--ctr-toolbox-item-icon-width": "var(--sjs-size-x3)",
    // "--ctr-toolbox-item-margin-horizontal-no-text": "var(--sjs-spacing-x05)",
    // "--ctr-toolbox-item-opacity-submenu": 1,
    // "--ctr-toolbox-item-padding-bottom-submenu": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-item-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-item-padding-left-no-text": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-item-padding-left-submenu": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-item-padding-left": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-item-padding-right-no-text": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-item-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-item-padding-top-submenu": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-item-padding-top": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-item-shadow-hovered-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-toolbox-item-shadow-hovered-1-color': '#00000000',
    // "--ctr-toolbox-item-shadow-hovered-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-toolbox-item-shadow-hovered-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-toolbox-item-shadow-hovered-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-toolbox-item-shadow-hovered-2-blur": "var(--ctr-shadow-small-blur)",
    '--ctr-toolbox-item-shadow-hovered-2-color': '#00000000',
    // "--ctr-toolbox-item-shadow-hovered-2-offset-x": "var(--ctr-shadow-small-offset-x)",
    // "--ctr-toolbox-item-shadow-hovered-2-offset-y": "var(--ctr-shadow-small-offset-y)",
    // "--ctr-toolbox-item-shadow-hovered-2-spread": "var(--ctr-shadow-small-spread)",
    // "--ctr-toolbox-item-shadow-pressed-blur": "var(--ctr-shadow-small-blur)",
    '--ctr-toolbox-item-shadow-pressed-color': '#00000000',
    // "--ctr-toolbox-item-shadow-pressed-offset-x": "var(--ctr-shadow-small-offset-x)",
    // "--ctr-toolbox-item-shadow-pressed-offset-y": "var(--ctr-shadow-small-offset-y)",
    // "--ctr-toolbox-item-shadow-pressed-spread": "var(--ctr-shadow-small-spread)",
    '--ctr-toolbox-item-shadow-subitem-1-color': '#00000000',
    '--ctr-toolbox-item-shadow-subitem-2-color': '#00000000',
    '--ctr-toolbox-item-submenu-button-background-color-hovered': colors.backgroundLight,
    '--ctr-toolbox-item-submenu-button-background-color': colors.background,
    // "--ctr-toolbox-item-submenu-button-corner-radius": "var(--sjs-corner-radius-x05)",
    '--ctr-toolbox-item-submenu-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-toolbox-item-submenu-button-icon-height": "var(--sjs-size-x2)",
    // "--ctr-toolbox-item-submenu-button-icon-width": "var(--sjs-size-x2)",
    // "--ctr-toolbox-item-submenu-button-margin-right": "var(--sjs-spacing-x1n)",
    // "--ctr-toolbox-item-submenu-button-padding-bottom": "var(--sjs-spacing-x05)",
    // "--ctr-toolbox-item-submenu-button-padding-left": "var(--sjs-spacing-x05)",
    // "--ctr-toolbox-item-submenu-button-padding-right": "var(--sjs-spacing-x05)",
    // "--ctr-toolbox-item-submenu-button-padding-top": "var(--sjs-spacing-x05)",
    '--ctr-toolbox-item-text-color-hovered': colors.textColor,
    '--ctr-toolbox-item-text-color-pressed': colors.textColor,
    '--ctr-toolbox-item-text-color-submenu': colors.textColor,
    '--ctr-toolbox-item-text-color': colors.textColor,
    // "--ctr-toolbox-item-text-opacity-disabled": 0.25,
    // "--ctr-toolbox-item-text-opacity-pressed": 0.5,
    // "--ctr-toolbox-margin-left-compact": "0px",
    // "--ctr-toolbox-min-width": "var(--sjs-size-x32)",
    // "--ctr-toolbox-padding-bottom": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-padding-top": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-scrollbar-left": "auto",
    // "--ctr-toolbox-scrollbar-right": "0",
    // "--ctr-toolbox-scroller-align-items": "flex-start",
    // "--ctr-toolbox-search-border-width-bottom": "var(--sjs-stroke-x1)",
    '--ctr-toolbox-search-clear-button-background-color-hovered': 'var(--sjs-semantic-red-background-10)',
    '--ctr-toolbox-search-clear-button-icon-color-hovered': 'var(--sjs-semantic-red-background-500)',
    '--ctr-toolbox-search-clear-button-icon-color': 'var(--sjs-layer-1-foreground-50)',
    // "--ctr-toolbox-search-gap": "var(--sjs-spacing-x1)",
    '--ctr-toolbox-search-icon-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-search-icon-color': 'var(--sjs-primary-background-500)',
    // "--ctr-toolbox-search-icon-height": "var(--sjs-size-x3)",
    // "--ctr-toolbox-search-icon-width": "var(--sjs-size-x3)",
    // "--ctr-toolbox-search-padding-bottom": "var(--sjs-spacing-x250)",
    // "--ctr-toolbox-search-padding-left": "var(--sjs-spacing-x3)",
    // "--ctr-toolbox-search-padding-right": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-search-padding-top": "var(--sjs-spacing-x250)",
    '--ctr-toolbox-search-text-color-placeholder': 'var(--sjs-layer-1-foreground-50)',
    '--ctr-toolbox-search-text-color': colors.textColor,
    '--ctr-toolbox-separator-color': colors.borderColor,
    // "--ctr-toolbox-separator-height": "var(--sjs-size-x0125)",
    // "--ctr-toolbox-separator-max-width": "var(--sjs-size-max)",
    // "--ctr-toolbox-separator-padding-bottom": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-separator-padding-left-compact": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-separator-padding-left": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-separator-padding-right-compact": "var(--sjs-spacing-x2)",
    // "--ctr-toolbox-separator-padding-right": "0px",
    // "--ctr-toolbox-separator-padding-top": "var(--sjs-spacing-x1)",
    // "--ctr-toolbox-shadow-floating-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-toolbox-shadow-floating-1-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-toolbox-shadow-floating-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-toolbox-shadow-floating-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-toolbox-shadow-floating-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-toolbox-shadow-floating-2-blur": "var(--ctr-shadow-large-blur)",
    '--ctr-toolbox-shadow-floating-2-color': 'var(--ctr-shadow-large-color)',
    // "--ctr-toolbox-shadow-floating-2-offset-x": "var(--ctr-shadow-large-offset-x)",
    // "--ctr-toolbox-shadow-floating-2-offset-y": "var(--ctr-shadow-large-offset-y)",
    // "--ctr-toolbox-shadow-floating-2-spread": "var(--ctr-shadow-large-spread)",
    '--ctr-toolbox-submenu-background-color': colors.background,
    // "--ctr-toolbox-submenu-corner-radius": "var(--sjs-corner-radius-x1)",
    // "--ctr-toolbox-submenu-group-border-width-bottom": "var(--sjs-stroke-x1)",
    // "--ctr-toolbox-submenu-group-margin-bottom-last": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-submenu-group-margin-bottom": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-submenu-group-margin-left": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-submenu-group-margin-right": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-submenu-group-margin-top": "var(--sjs-spacing-x150)",
    // "--ctr-toolbox-submenu-item-min-width": "calc(17 * 8px)",
    // "--ctr-toolbox-submenu-margin-left": "0px",
    // "--ctr-toolbox-submenu-margin-top": "var(--sjs-spacing-x1n)",
    // "--ctr-toolbox-submenu-shadow-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-toolbox-submenu-shadow-1-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-toolbox-submenu-shadow-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-toolbox-submenu-shadow-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-toolbox-submenu-shadow-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-toolbox-submenu-shadow-2-blur": "var(--ctr-shadow-large-blur)",
    '--ctr-toolbox-submenu-shadow-2-color': 'var(--ctr-shadow-large-color)',
    // "--ctr-toolbox-submenu-shadow-2-offset-x": "var(--ctr-shadow-large-offset-x)",
    // "--ctr-toolbox-submenu-shadow-2-offset-y": "var(--ctr-shadow-large-offset-y)",
    // "--ctr-toolbox-submenu-shadow-2-spread": "var(--ctr-shadow-large-spread)",
    '--ctr-tooltip-background-color': colors.background,
    // "--ctr-tooltip-corder-radius": "var(--sjs-corner-radius-x075)",
    // "--ctr-tooltip-padding-bottom": "var(--sjs-spacing-x2)",
    // "--ctr-tooltip-padding-left": "var(--sjs-spacing-x3)",
    // "--ctr-tooltip-padding-right": "var(--sjs-spacing-x3)",
    // "--ctr-tooltip-padding-top": "var(--sjs-spacing-x2)",
    // "--ctr-tooltip-pointer-height": "var(--sjs-size-x05)",
    // "--ctr-tooltip-shadow-1-blur": "var(--ctr-shadow-medium-blur)",
    '--ctr-tooltip-shadow-1-color': 'var(--ctr-shadow-medium-color)',
    // "--ctr-tooltip-shadow-1-offset-x": "var(--ctr-shadow-medium-offset-x)",
    // "--ctr-tooltip-shadow-1-offset-y": "var(--ctr-shadow-medium-offset-y)",
    // "--ctr-tooltip-shadow-1-spread": "var(--ctr-shadow-medium-spread)",
    // "--ctr-tooltip-shadow-2-blur": "var(--ctr-shadow-small-blur)",
    '--ctr-tooltip-shadow-2-color': 'var(--ctr-shadow-small-color)',
    // "--ctr-tooltip-shadow-2-offset-x": "var(--ctr-shadow-small-offset-x)",
    // "--ctr-tooltip-shadow-2-offset-y": "var(--ctr-shadow-small-offset-y)",
    // "--ctr-tooltip-shadow-2-spread": "var(--ctr-shadow-small-spread)",
    '--lbr-action-button-icon-color-negative': 'var(--sjs-semantic-red-background-500)',
    // "--lbr-notification-button-corner-radius": "var(--sjs-corner-radius-x1)",
    // "--lbr-notification-padding-bottom-with-button": "var(--sjs-spacing-x3)",
    // "--lbr-notification-padding-left-with-button": "var(--sjs-spacing-x2)",
    // "--lbr-notification-padding-left": "var(--sjs-spacing-x2)",
    // "--lbr-notification-padding-right": "var(--sjs-spacing-x2)",
    // "--lbr-notification-padding-top-with-button": "var(--sjs-spacing-x3)",
    // "--lbr-shadow-inner-blur": "2px",
    '--lbr-shadow-inner-color': 'var(--sjs-special-shadow)',
    // "--lbr-shadow-inner-offset-x": "0px",
    // "--lbr-shadow-inner-offset-y": "1px",
    // "--lbr-shadow-inner-spread": "0px",
    // "--lbr-shadow-large-blur": "32px",
    '--lbr-shadow-large-color': 'var(--sjs-special-glow)',
    // "--lbr-shadow-large-offset-x": "0px",
    // "--lbr-shadow-large-offset-y": "16px",
    // "--lbr-shadow-large-spread": "0px",
    // "--lbr-shadow-medium-blur": "8px",
    '--lbr-shadow-medium-color': 'var(--sjs-special-glow)',
    // "--lbr-shadow-medium-offset-x": "0px",
    // "--lbr-shadow-medium-offset-y": "2px",
    // "--lbr-shadow-medium-spread": "0px",
    // "--lbr-shadow-small-blur": "2px",
    '--lbr-shadow-small-color': 'var(--sjs-special-shadow)',
    // "--lbr-shadow-small-offset-x": "0px",
    // "--lbr-shadow-small-offset-y": "1px",
    // "--lbr-shadow-small-spread": "0px",
    // "--lbr-shadow-x-large-blur": "64px",
    '--lbr-shadow-x-large-color': 'var(--sjs-special-glow)',
    // "--lbr-shadow-x-large-offset-x": "0px",
    // "--lbr-shadow-x-large-offset-y": "32px",
    // "--lbr-shadow-x-large-spread": "0px",
  },
  themeName: 'openlane',
  colorPalette: 'dark',
  isPanelless: true,
}
