'use client'
import { type ColumnDef } from '@tanstack/react-table'
import { GlobeIcon, LockIcon, StarsIcon } from 'lucide-react'
import { type Group, type User } from '@repo/codegen/src/schema'
import AvatarList from '@/components/shared/avatar-list/avatar-list'
import TagChip from '@/components/shared/tag-chip.tsx/tag-chip'
import { UserCell } from '@/components/shared/crud-base/columns/user-cell'
import { DateCell } from '@/components/shared/crud-base/columns/date-cell'
import { toBase64DataUri } from '@/lib/image-utils'
import { TruncatedCell } from '@repo/ui/data-table'

type Params = {
  userMap?: Record<string, User>
}

export const getGroupTableColumns = ({ userMap }: Params) => {
  const columns: ColumnDef<Group>[] = [
    {
      accessorKey: 'id',
      header: 'ID',
      size: 270,
      minSize: 270,
      maxSize: 270,
      cell: ({ row }) => <div className="text-muted-foreground">{row.original.id}</div>,
    },
    {
      header: 'Display Name',
      accessorKey: 'displayName',
      cell: ({ row }) => {
        const isAutoGenerated = row.original.isManaged
        return (
          <div className="flex gap-2">
            {isAutoGenerated ? (
              <div className="flex gap-1">
                <StarsIcon className="mt-0.5" width={16} height={16} />
                <div className="flex flex-col gap-1">
                  <span className="text-sm whitespace-nowrap">{row.original.displayName}</span>
                  <p className="text-xs text-text-light">Prebuilt</p>
                </div>
              </div>
            ) : (
              <span>{row.original.displayName}</span>
            )}
          </div>
        )
      },
    },
    {
      header: 'Name',
      accessorKey: 'name',
      cell: ({ row }) => {
        const isAutoGenerated = row.original.isManaged
        return (
          <div className="flex gap-2">
            {isAutoGenerated ? (
              <div className="flex gap-1">
                <StarsIcon className="mt-0.5" width={16} height={16} />
                <div className="flex flex-col gap-1">
                  <span className="text-sm whitespace-nowrap">{row.original.name}</span>
                  <p className="text-xs text-text-light">Prebuilt</p>
                </div>
              </div>
            ) : (
              <span>{row.original.name}</span>
            )}
          </div>
        )
      },
    },
    {
      header: 'Description',
      accessorKey: 'description',
      cell: ({ row }) => (
        <div>
          <TruncatedCell className="whitespace-normal line-clamp-2">{(row.getValue('description') as string) || '-'}</TruncatedCell>
          {!!row.original?.tags?.length && (
            <div className="mt-2 border-t border-dashed pt-2 flex flex-wrap gap-2">
              {row.original.tags.map((tag: string, i: number) => (
                <TagChip key={i} tag={tag} />
              ))}
            </div>
          )}
        </div>
      ),
    },
    {
      header: 'Visibility',
      accessorKey: 'visibility',
      cell: ({ row }) => {
        const value = row.original.setting?.visibility
        return (
          <span className="flex items-center gap-2 capitalize">
            {value === 'PUBLIC' ? <GlobeIcon height={18} /> : <LockIcon height={18} />}
            {value?.toLowerCase()}
          </span>
        )
      },
    },
    {
      header: 'Members',
      accessorKey: 'members',
      cell: ({ row }) => {
        const members = row.original.members.edges?.map((user) => user?.node?.user as User) || []
        return members.length > 0 ? (
          <AvatarList
            max={10}
            data={members.map((user) => ({
              id: user.id,
              imageUrl: (user.avatarFile?.base64 ? toBase64DataUri(user.avatarFile.base64) : null) ?? user.avatarRemoteURL ?? undefined,
              fallback: user.firstName?.substring(0, 2) ?? undefined,
              displayName: user?.displayName ?? undefined,
            }))}
          />
        ) : (
          <span className="text-gray-500">No members</span>
        )
      },
    },
    {
      accessorKey: 'createdBy',
      header: 'Created by',
      size: 200,
      cell: ({ row }) => <UserCell user={userMap?.[row.original.createdBy ?? '']} />,
    },
    {
      accessorKey: 'createdAt',
      header: 'Created At',
      size: 150,
      cell: ({ cell }) => <DateCell value={cell.getValue() as string} />,
    },
    {
      accessorKey: 'updatedBy',
      header: 'Updated By',
      size: 200,
      cell: ({ row }) => <UserCell user={userMap?.[row.original.updatedBy ?? '']} />,
    },
    {
      accessorKey: 'updatedAt',
      header: 'Last Updated',
      size: 100,
      cell: ({ cell }) => <DateCell value={cell.getValue() as string} variant="timesince" />,
    },
  ]

  const mappedColumns = columns
    .filter((column): column is { accessorKey: string; header: string } => 'accessorKey' in column && typeof column.accessorKey === 'string' && typeof column.header === 'string')
    .map((column) => ({
      accessorKey: column.accessorKey,
      header: column.header,
    }))

  return { columns, mappedColumns }
}
