import { type ObjectTypes } from '@repo/codegen/src/type-names'
import { PlanEnum } from '@/lib/subscription-plan/plan-enum'

export const MODULES_BY_OBJECT_TYPE: Record<ObjectTypes, PlanEnum[]> = {
  ApiToken: [PlanEnum.BASE_MODULE],
  ActionPlan: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON, PlanEnum.RISK_MANAGEMENT_ADDON, PlanEnum.ENTITY_MANAGEMENT_MODULE],
  Assessment: [PlanEnum.COMPLIANCE_MODULE],
  AssessmentResponse: [PlanEnum.COMPLIANCE_MODULE],
  Asset: [PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  Campaign: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.TRUST_CENTER_MODULE],
  CampaignTarget: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.TRUST_CENTER_MODULE],
  CheckResult: [PlanEnum.BASE_MODULE],
  Contact: [PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  Control: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.TRUST_CENTER_MODULE],
  ControlImplementation: [PlanEnum.COMPLIANCE_MODULE],
  ControlObjective: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON],
  ControlReport: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.TRUST_CENTER_MODULE],
  CustomDomain: [PlanEnum.TRUST_CENTER_MODULE],
  CustomTypeEnum: [PlanEnum.BASE_MODULE],
  DnsVerification: [PlanEnum.TRUST_CENTER_MODULE],
  DirectoryAccount: [PlanEnum.BASE_MODULE],
  DirectoryGroup: [PlanEnum.BASE_MODULE],
  DirectoryMembership: [PlanEnum.BASE_MODULE],
  DirectorySyncRun: [PlanEnum.BASE_MODULE],
  Discussion: [PlanEnum.BASE_MODULE],
  DocumentData: [PlanEnum.COMPLIANCE_MODULE],
  EmailTemplate: [PlanEnum.BASE_MODULE],
  Entity: [PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  EntityType: [PlanEnum.BASE_MODULE],
  Event: [PlanEnum.BASE_MODULE],
  Evidence: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON],
  Export: [PlanEnum.BASE_MODULE],
  File: [PlanEnum.BASE_MODULE],
  Finding: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  FindingControl: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  Group: [PlanEnum.BASE_MODULE],
  GroupMembership: [PlanEnum.BASE_MODULE],
  GroupPermission: [PlanEnum.BASE_MODULE],
  GroupSetting: [PlanEnum.BASE_MODULE],
  Hush: [PlanEnum.BASE_MODULE],
  IdentityHolder: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  Integration: [PlanEnum.BASE_MODULE],
  InternalPolicy: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON],
  Invite: [PlanEnum.BASE_MODULE],
  JobResult: [PlanEnum.COMPLIANCE_MODULE],
  JobRunner: [PlanEnum.COMPLIANCE_MODULE],
  JobRunnerRegistrationToken: [PlanEnum.COMPLIANCE_MODULE],
  JobRunnerToken: [PlanEnum.COMPLIANCE_MODULE],
  JobTemplate: [PlanEnum.COMPLIANCE_MODULE],
  MappableDomain: [PlanEnum.TRUST_CENTER_MODULE],
  MappedControl: [PlanEnum.COMPLIANCE_MODULE],
  Narrative: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON],
  Note: [PlanEnum.BASE_MODULE],
  Notification: [PlanEnum.BASE_MODULE],
  NotificationPreference: [PlanEnum.BASE_MODULE],
  NotificationTemplate: [PlanEnum.BASE_MODULE],
  Onboarding: [PlanEnum.BASE_MODULE],
  OrgMembership: [PlanEnum.BASE_MODULE],
  OrgSubscription: [PlanEnum.BASE_MODULE],
  Organization: [PlanEnum.BASE_MODULE],
  OrganizationSetting: [PlanEnum.BASE_MODULE],
  PersonalAccessToken: [PlanEnum.BASE_MODULE],
  Platform: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.REGISTRY_MODULE],
  PolicySummary: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON],
  Procedure: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON, PlanEnum.RISK_MANAGEMENT_ADDON, PlanEnum.ENTITY_MANAGEMENT_MODULE],
  Program: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.ENTITY_MANAGEMENT_MODULE],
  ProgramMembership: [PlanEnum.COMPLIANCE_MODULE],
  Remediation: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.RISK_MANAGEMENT_ADDON, PlanEnum.COMPLIANCE_MODULE],
  Review: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.VULNERABILITY_MANAGEMENT_MODULE],
  Risk: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.RISK_MANAGEMENT_ADDON],
  SlaDefinition: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  Scan: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  ScheduledJob: [PlanEnum.COMPLIANCE_MODULE],
  ScheduledJobRun: [PlanEnum.COMPLIANCE_MODULE],
  Standard: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.POLICY_MANAGEMENT_ADDON, PlanEnum.RISK_MANAGEMENT_ADDON, PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.TRUST_CENTER_MODULE],
  Subcontrol: [PlanEnum.COMPLIANCE_MODULE],
  Subprocessor: [PlanEnum.TRUST_CENTER_MODULE, PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  Subscriber: [PlanEnum.BASE_MODULE],
  SystemDetail: [PlanEnum.COMPLIANCE_MODULE, PlanEnum.REGISTRY_MODULE],
  TfaSetting: [PlanEnum.BASE_MODULE],
  TagDefinition: [PlanEnum.BASE_MODULE],
  Task: [PlanEnum.BASE_MODULE],
  Template: [PlanEnum.BASE_MODULE],
  TrustCenter: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterCompliance: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterDoc: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterEntity: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterFaq: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterNdaRequest: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterSetting: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterSubprocessor: [PlanEnum.TRUST_CENTER_MODULE],
  TrustCenterWatermarkConfig: [PlanEnum.TRUST_CENTER_MODULE],
  User: [PlanEnum.BASE_MODULE],
  UserSetting: [PlanEnum.BASE_MODULE],
  VendorRiskScore: [PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  VendorScoringConfig: [PlanEnum.ENTITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  Vulnerability: [PlanEnum.VULNERABILITY_MANAGEMENT_MODULE, PlanEnum.COMPLIANCE_MODULE],
  Webauthn: [PlanEnum.BASE_MODULE],
  WorkflowAssignment: [PlanEnum.BASE_MODULE],
  WorkflowAssignmentTarget: [PlanEnum.BASE_MODULE],
  WorkflowDefinition: [PlanEnum.BASE_MODULE],
  WorkflowEvent: [PlanEnum.BASE_MODULE],
  WorkflowInstance: [PlanEnum.BASE_MODULE],
  WorkflowObjectRef: [PlanEnum.BASE_MODULE],
  WorkflowProposal: [PlanEnum.BASE_MODULE],
}

export const UPGRADE_MODULES_BY_OBJECT_TYPE = Object.fromEntries(
  Object.entries(MODULES_BY_OBJECT_TYPE).map(([objectType, modules]) => [objectType, modules.filter((module) => module !== PlanEnum.BASE_MODULE)]),
) as Record<ObjectTypes, PlanEnum[]>
