import { type ITheme, patchLegacyCSSVariables } from 'survey-core'
import DefaultDark from 'survey-core/themes/default-dark'

// values pulled from the openlane dark mode tokens in packages/ui/src/styles.css
const colors = {
  primary: '#60e8c9',
  secondary: '#2dcdad',
  surface: '#09151d',
  background: '#09151d',
  backgroundDim: '#162431',
  backgroundLight: '#233440',
  textColor: '#ffffff',
  textColorDim: '#9aa5b0',
  inputPlaceholderColor: '#9aa5b0',
}

// https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/themes/predefined-themes/default/dark.css
// exported from https://surveyjs.io/create-free-survey - use the theme tab, go to theme,then use the export button
const SJS_THEME = {
  '--sjs-corner-radius': '8px',
  '--sjs-base-unit': '8px',
  '--sjs-font-size': '14px',
  '--sjs-font-editorfont-size': '14px',
  '--sjs-font-questiontitle-weight': '500',
  '--sjs-font-surveytitle-size': '24px',
  '--sjs-font-surveytitle-weight': '600',
  '--foreground': colors.textColor,
  '--background': colors.background,
  '--background-dim-light': colors.surface,
  '--primary': colors.primary,
  '--secondary': colors.secondary,
  '--secondary-light': colors.secondary,
  '--sjs-shadow-small': '0px 1px 2px 0px rgba(0, 0, 0, 0.35), 0px 0px 0px 1px #394b58',
  '--sjs-shadow-inner': 'inset 0px 0px 0px 1px #394b58',
  '--sjs-border-default': 'rgba(255, 255, 255, 0.12)',
  '--sjs-border-light': 'rgba(255, 255, 255, 0.08)',
  // title band and form body panels in the survey viewer (see survey-viewer.css);
  // raised a step from the page background so the panels read in dark mode
  '--ol-survey-panel-backcolor': colors.backgroundDim,
  '--sjs-general-backcolor': colors.background,
  '--sjs-general-backcolor-dark': colors.backgroundLight,
  '--sjs-general-backcolor-dim-light': colors.backgroundDim,
  '--sjs-general-backcolor-dim-dark': '#162431',
  '--sjs-general-forecolor': colors.textColor,
  '--sjs-general-forecolor-light': colors.textColorDim,
  '--sjs-general-dim-forecolor': 'rgba(255, 255, 255, 0.79)',
  '--sjs-general-dim-forecolor-light': 'rgba(255, 255, 255, 0.45)',
  '--sjs-secondary-backcolor': colors.secondary,
  '--sjs-secondary-backcolor-light': colors.secondary,
  '--sjs-secondary-backcolor-semi-light': colors.secondary,
  '--sjs-secondary-forecolor': colors.surface,
  '--sjs-secondary-forecolor-light': 'rgba(9, 21, 29, 0.25)',
  '--sjs-shadow-small-reset': '0px 0px 0px 0px rgba(0, 0, 0, 0.35)',
  '--sjs-shadow-medium': '0px 2px 6px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-shadow-inner-reset': 'inset 0px 0px 0px 0px rgba(0, 0, 0, 0.2)',
  '--sjs-border-inside': 'rgba(255, 255, 255, 0.08)',
  '--sjs-special-red-forecolor': '#ffffff',
  '--sjs-special-green': 'rgba(33, 197, 93, 1)',
  '--sjs-special-green-light': 'rgba(33, 197, 93, 0.1)',
  '--sjs-special-green-forecolor': '#ffffff',
  '--sjs-special-blue': 'rgba(99, 146, 255, 1)',
  '--sjs-special-blue-light': 'rgba(99, 146, 255, 0.1)',
  '--sjs-special-blue-forecolor': '#ffffff',
  '--sjs-special-yellow': 'rgba(255, 132, 44, 1)',
  '--sjs-special-yellow-light': 'rgba(255, 132, 44, 0.1)',
  '--sjs-special-yellow-forecolor': '#ffffff',
  '--sjs-general-backcolor-dim': colors.backgroundDim,
  '--sjs-primary-backcolor': colors.primary,
  '--sjs-primary-backcolor-dark': '#2dcdad',
  '--sjs-primary-backcolor-light': 'rgba(96, 232, 201, 0.07)',
  '--sjs-primary-forecolor': colors.surface,
  '--sjs-primary-forecolor-light': 'rgba(9, 21, 29, 0.25)',
  '--sjs-special-red': 'rgba(244, 91, 80, 1)',
  '--sjs-special-red-light': 'rgba(244, 91, 80, 0.1)',
  '--sjs-questionpanel-hovercolor': colors.background,
  '--sjs-questionpanel-backcolor': colors.backgroundLight,
  '--sjs-question-background': colors.backgroundLight,
  '--sjs-editor-background': colors.backgroundLight,
  '--sjs-editorpanel-backcolor': colors.backgroundLight,
  '--sjs-font-pagetitle-color': colors.textColor,
  '--sjs-font-pagedescription-color': colors.textColorDim,
  '--sjs-font-questiontitle-color': colors.textColor,
  '--sjs-font-questiondescription-color': colors.textColorDim,
  '--sjs-font-editorfont-color': colors.textColor,
  '--sjs-font-editorfont-placeholdercolor': colors.inputPlaceholderColor,
  '--sjs-secondary-background-800': '#005e4d',
  '--sjs-secondary-background-700': '#00795f',
  '--sjs-secondary-background-600': '#009975',
  '--sjs-secondary-background-500': '#2dcdad',
  '--sjs-secondary-background-400': '#60e8c9',
  '--sjs-secondary-background-300': '#9af5dd',
  '--sjs-secondary-background-200': '#c8ffef',
  '--sjs-secondary-background-100': '#e0fff7',
  '--sjs-secondary-background-10': '#e0fff7',
  '--sjs-secondary-background-25': '#e0fff7',
  '--sjs-secondary-background-50': '#e0fff7',
  '--sjs-primary-foreground-25': '#ffffff',
  '--sjs-primary-foreground-50': '#ffffff',
  '--sjs-primary-foreground-100': '#ffffff',
  '--sjs-primary-foreground-200': '#ffffff',
  '--sjs-primary-foreground-300': '#ffffff',
  '--sjs-primary-foreground-400': '#ffffff',
  '--sjs-primary-foreground-500': '#ffffff',
  '--sjs-primary-foreground-600': '#ffffff',
  '--sjs-primary-foreground-700': '#ffffff',
  '--sjs-primary-foreground-800': '#ffffff',
  '--sjs-primary-foreground-900': '#ffffff',
  '--sjs-primary-background-500': '#60e8c9',
  '--sjs-layer-1-foreground-100': '#ffffff',
  '--sjs-layer-1-foreground-200': '#ffffff',
  '--sjs-layer-1-foreground-300': '#ffffff',
  '--sjs-layer-1-foreground-400': '#ffffff',
  '--sjs-layer-1-foreground-500': '#ffffff',
  '--sjs-layer-1-foreground-600': '#ffffff',
  '--sjs-layer-1-foreground-700': '#ffffff',
  '--sjs-layer-1-foreground-800': '#ffffff',
  '--sjs-font-surveytitle-family': 'var(--font-outfit)',
  '--sjs-font-headertitle-family': 'var(--font-outfit)',
  '--sjs-font-headertitle-color': colors.textColor,
  '--sjs-font-headerdescription-color': colors.textColorDim,
  '--sjs-font-headertitle-weight': '700',
  '--sjs-header-backcolor': '#09151d',
  '--sjs-article-font-xx-large-textDecoration': 'none',
  '--sjs-article-font-xx-large-fontWeight': '400',
  '--sjs-article-font-xx-large-fontStyle': 'normal',
  '--sjs-article-font-xx-large-fontStretch': 'normal',
  '--sjs-article-font-xx-large-letterSpacing': '0',
  '--sjs-article-font-xx-large-lineHeight': '64px',
  '--sjs-article-font-xx-large-paragraphIndent': '0px',
  '--sjs-article-font-xx-large-textCase': 'none',
  '--sjs-article-font-x-large-textDecoration': 'none',
  '--sjs-article-font-x-large-fontWeight': '400',
  '--sjs-article-font-x-large-fontStyle': 'normal',
  '--sjs-article-font-x-large-fontStretch': 'normal',
  '--sjs-article-font-x-large-letterSpacing': '0',
  '--sjs-article-font-x-large-lineHeight': '56px',
  '--sjs-article-font-x-large-paragraphIndent': '0px',
  '--sjs-article-font-x-large-textCase': 'none',
  '--sjs-article-font-large-textDecoration': 'none',
  '--sjs-article-font-large-fontWeight': '400',
  '--sjs-article-font-large-fontStyle': 'normal',
  '--sjs-article-font-large-fontStretch': 'normal',
  '--sjs-article-font-large-letterSpacing': '0',
  '--sjs-article-font-large-lineHeight': '40px',
  '--sjs-article-font-large-paragraphIndent': '0px',
  '--sjs-article-font-large-textCase': 'none',
  '--sjs-article-font-medium-textDecoration': 'none',
  '--sjs-article-font-medium-fontWeight': '400',
  '--sjs-article-font-medium-fontStyle': 'normal',
  '--sjs-article-font-medium-fontStretch': 'normal',
  '--sjs-article-font-medium-letterSpacing': '0',
  '--sjs-article-font-medium-lineHeight': '32px',
  '--sjs-article-font-medium-paragraphIndent': '0px',
  '--sjs-article-font-medium-textCase': 'none',
  '--sjs-article-font-default-textDecoration': 'none',
  '--sjs-article-font-default-fontWeight': '400',
  '--sjs-article-font-default-fontStyle': 'normal',
  '--sjs-article-font-default-fontStretch': 'normal',
  '--sjs-article-font-default-letterSpacing': '0',
  '--sjs-article-font-default-lineHeight': '28px',
  '--sjs-article-font-default-paragraphIndent': '0px',
  '--sjs-article-font-default-textCase': 'none',
  '--sjs-layer-1-background-500': colors.background,
  '--sjs-layer-1-background-400': colors.backgroundDim,
  '--sjs-layer-2-foreground-100': '#ffffff',
  '--sjs-layer-2-foreground-50': 'rgba(255, 255, 255, 0.5)',
  '--sjs-layer-2-background-500': colors.backgroundDim,
  '--sjs-layer-2-background-400': colors.background,
  '--sjs-layer-3-foreground-100': '#ffffff',
  '--sjs-layer-3-foreground-50': 'rgba(255, 255, 255, 0.5)',
  '--sjs-layer-3-background-500': colors.backgroundLight,
  '--sjs-layer-3-background-400': '#162431',
  '--sjs-layer-1-foreground-50': 'rgba(255, 255, 255, 0.5)',
  '--sjs-special-background': colors.surface,
  '--background-dim': colors.backgroundDim,
}

const openlaneCssVariables: Record<string, string> = { ...SJS_THEME }
patchLegacyCSSVariables(openlaneCssVariables, true)

export const darkTheme: ITheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'scroll',
  backgroundOpacity: 1,
  cssVariables: { ...DefaultDark.cssVariables, ...openlaneCssVariables },
  themeName: 'openlane',
  colorPalette: 'dark',
  isPanelless: true,
}
