import { type ITheme, patchLegacyCSSVariables } from 'survey-core'
import DefaultLight from 'survey-core/themes/default-light'

// values pulled from the openlane light mode tokens in packages/ui/src/styles.css
const colors = {
  primary: '#2dcdad',
  primaryDark: '#0e937c',
  primaryLight: '#9af5dc',
  primaryForeground: '#052e2a',
  surface: '#f4f9fa',
  background: '#ffffff',
  backgroundDim: '#eff4f5',
  borderColor: '#e1e7ea',
  textColor: '#09151d',
  textColorDim: '#6b7682',
  inputPlaceholderColor: '#9aa5b0',
}

const SJS_THEME = {
  // title band and form body panels in the survey viewer (see survey-viewer.css);
  // white so the panels read against the page's dim surface
  '--ol-survey-panel-backcolor': colors.background,
  '--sjs-general-forecolor': colors.textColor,
  '--sjs-questionpanel-hovercolor': colors.surface,
  '--sjs-corner-radius': '8px',
  '--sjs-base-unit': '8px',
  '--sjs-font-size': '14px',
  '--sjs-font-editorfont-size': '14px',
  '--sjs-font-questiontitle-weight': '500',
  '--sjs-font-surveytitle-size': '24px',
  '--sjs-font-surveytitle-weight': '600',
  '--sjs-font-pagetitle-color': colors.textColor,
  '--sjs-font-pagedescription-color': colors.textColorDim,
  '--sjs-font-questiontitle-color': colors.textColor,
  '--sjs-font-questiondescription-color': colors.textColorDim,
  '--sjs-font-editorfont-color': colors.textColor,
  '--sjs-editorpanel-backcolor': colors.background,
  '--sjs-font-editorfont-placeholdercolor': colors.inputPlaceholderColor,
  '--sjs-shadow-small': '0px 1px 2px 0px rgba(9, 21, 29, 0.05), 0px 0px 0px 1px #e1e7ea',
  '--sjs-shadow-inner': 'inset 0px 0px 0px 1px #e1e7ea',
  '--sjs-border-default': colors.borderColor,
  '--sjs-border-light': colors.borderColor,
  '--sjs-general-backcolor': colors.background,
  '--sjs-general-backcolor-dark': colors.borderColor,
  '--sjs-questionpanel-backcolor': colors.background,
  '--sjs-question-background': colors.background,
  '--sjs-editor-background': colors.background,
  '--sjs-general-dim-forecolor': colors.textColor,
  '--sjs-general-dim-forecolor-light': colors.textColorDim,
  '--foreground': colors.textColor,
  '--primary-foreground': colors.primaryForeground,
  '--sjs-secondary-backcolor': colors.primary,
  '--sjs-secondary-backcolor-light': colors.primaryLight,
  '--sjs-secondary-backcolor-semi-light': colors.primaryLight,
  '--sjs-secondary-forecolor': colors.primaryForeground,
  '--sjs-secondary-forecolor-25': colors.primaryForeground,
  '--sjs-secondary-forecolor-50': colors.primaryForeground,
  '--sjs-secondary-foreground-100': colors.primaryForeground,
  '--sjs-secondary-foreground-200': colors.primaryForeground,
  '--sjs-secondary-foreground-300': colors.primaryForeground,
  '--sjs-secondary-foreground-400': colors.primaryForeground,
  '--sjs-secondary-foreground-500': colors.primaryForeground,
  '--sjs-secondary-foreground-600': colors.primaryForeground,
  '--sjs-secondary-foreground-700': colors.primaryForeground,
  '--sjs-secondary-foreground-800': colors.primaryForeground,
  '--sjs-secondary-foreground-900': colors.primaryForeground,
  '--sjs-secondary-forecolor-light': colors.primaryForeground,
  '--sjs-layer-1-foreground-100': colors.textColor,
  '--sjs-layer-1-foreground-200': colors.textColor,
  '--sjs-layer-1-foreground-300': colors.textColor,
  '--sjs-layer-1-foreground-400': colors.textColor,
  '--sjs-layer-1-foreground-500': colors.textColor,
  '--sjs-layer-1-foreground-600': colors.textColor,
  '--sjs-layer-1-foreground-700': colors.textColor,
  '--sjs-layer-1-foreground-800': colors.textColor,
  '--sjs-shadow-small-reset': '0px 0px 0px 0px rgba(9, 21, 29, 0.1)',
  '--sjs-shadow-medium': '0px 2px 6px 0px rgba(9, 21, 29, 0.08)',
  '--sjs-shadow-large': '0px 8px 16px 0px rgba(9, 21, 29, 0.08)',
  '--sjs-shadow-inner-reset': 'inset 0px 0px 0px 0px rgba(9, 21, 29, 0.1)',
  '--sjs-border-inside': colors.borderColor,
  '--sjs-special-red-forecolor': '#ffffff',
  '--sjs-special-green': 'rgba(33, 197, 93, 1)',
  '--sjs-special-green-light': 'rgba(33, 197, 93, 0.1)',
  '--sjs-special-green-forecolor': '#ffffff',
  '--sjs-special-blue': 'rgba(99, 146, 255, 1)',
  '--sjs-special-blue-light': 'rgba(99, 146, 255, 0.1)',
  '--sjs-special-blue-forecolor': '#ffffff',
  '--sjs-special-yellow': 'rgba(255, 132, 44, 1)',
  '--sjs-special-yellow-light': 'rgba(255, 132, 44, 0.1)',
  '--sjs-special-yellow-forecolor': '#ffffff',
  '--sjs-article-font-xx-large-textDecoration': 'none',
  '--sjs-article-font-xx-large-fontWeight': '400',
  '--sjs-article-font-xx-large-fontStyle': 'normal',
  '--sjs-article-font-xx-large-fontStretch': 'normal',
  '--sjs-article-font-xx-large-letterSpacing': '0',
  '--sjs-article-font-xx-large-lineHeight': '64px',
  '--sjs-article-font-xx-large-paragraphIndent': '0px',
  '--sjs-article-font-xx-large-textCase': 'none',
  '--sjs-article-font-x-large-textDecoration': 'none',
  '--sjs-article-font-x-large-fontWeight': '400',
  '--sjs-article-font-x-large-fontStyle': 'normal',
  '--sjs-article-font-x-large-fontStretch': 'normal',
  '--sjs-article-font-x-large-letterSpacing': '0',
  '--sjs-article-font-x-large-lineHeight': '56px',
  '--sjs-article-font-x-large-paragraphIndent': '0px',
  '--sjs-article-font-x-large-textCase': 'none',
  '--sjs-article-font-large-textDecoration': 'none',
  '--sjs-article-font-large-fontWeight': '400',
  '--sjs-article-font-large-fontStyle': 'normal',
  '--sjs-article-font-large-fontStretch': 'normal',
  '--sjs-article-font-large-letterSpacing': '0',
  '--sjs-article-font-large-lineHeight': '40px',
  '--sjs-article-font-large-paragraphIndent': '0px',
  '--sjs-article-font-large-textCase': 'none',
  '--sjs-article-font-medium-textDecoration': 'none',
  '--sjs-article-font-medium-fontWeight': '400',
  '--sjs-article-font-medium-fontStyle': 'normal',
  '--sjs-article-font-medium-fontStretch': 'normal',
  '--sjs-article-font-medium-letterSpacing': '0',
  '--sjs-article-font-medium-lineHeight': '32px',
  '--sjs-article-font-medium-paragraphIndent': '0px',
  '--sjs-article-font-medium-textCase': 'none',
  '--sjs-article-font-default-textDecoration': 'none',
  '--sjs-article-font-default-fontWeight': '400',
  '--sjs-article-font-default-fontStyle': 'normal',
  '--sjs-article-font-default-fontStretch': 'normal',
  '--sjs-article-font-default-letterSpacing': '0',
  '--sjs-article-font-default-lineHeight': '28px',
  '--sjs-article-font-default-paragraphIndent': '0px',
  '--sjs-article-font-default-textCase': 'none',
  '--sjs-general-backcolor-dim': colors.backgroundDim,
  '--sjs-primary-backcolor': colors.primary,
  '--sjs-primary-backcolor-dark': colors.primaryDark,
  '--sjs-secondary-background-800': '#005e4d',
  '--sjs-secondary-background-700': '#00795f',
  '--sjs-secondary-background-600': '#009975',
  '--sjs-secondary-background-500': '#2dcdad',
  '--sjs-secondary-background-400': '#60e8c9',
  '--sjs-secondary-background-300': '#9af5dd',
  '--sjs-secondary-background-200': '#c8ffef',
  '--sjs-secondary-background-100': '#e0fff7',
  '--sjs-secondary-background-10': '#e0fff7',
  '--sjs-secondary-background-25': '#e0fff7',
  '--sjs-secondary-background-50': '#e0fff7',
  '--sjs-primary-foreground-25': colors.primaryForeground,
  '--sjs-primary-foreground-50': colors.primaryForeground,
  '--sjs-primary-foreground-100': colors.primaryForeground,
  '--sjs-primary-foreground-200': colors.primaryForeground,
  '--sjs-primary-foreground-300': colors.primaryForeground,
  '--sjs-primary-foreground-400': colors.primaryForeground,
  '--sjs-primary-foreground-500': colors.primaryForeground,
  '--sjs-primary-foreground-600': colors.primaryForeground,
  '--sjs-primary-foreground-700': colors.primaryForeground,
  '--sjs-primary-foreground-800': colors.primaryForeground,
  '--sjs-primary-foreground-900': colors.primaryForeground,
  '--sjs-primary-backcolor-light': 'rgba(45, 205, 173, 0.1)',
  '--sjs-primary-background-500': colors.primary,
  '--sjs-primary-forecolor': colors.primaryForeground,
  '--sjs-primary-forecolor-light': 'rgba(5, 46, 42, 0.25)',
  '--sjs-special-red': 'rgba(244, 91, 80, 1)',
  '--sjs-special-red-light': 'rgba(244, 91, 80, 0.1)',
  '--sjs-font-surveytitle-family': 'var(--font-outfit)',
  '--sjs-font-headertitle-family': 'var(--font-outfit)',
  '--sjs-default-font-family': 'var(--font-outfit)',
  '--sjs-font-family': 'var(--font-outfit)',
  '--sjs-font-headertitle-color': colors.textColor,
  '--sjs-font-headerdescription-color': colors.textColorDim,
  '--sjs-header-backcolor': colors.background,
}

const openlaneCssVariables: Record<string, string> = { ...SJS_THEME }
patchLegacyCSSVariables(openlaneCssVariables, true)

export const lightTheme: ITheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'scroll',
  backgroundOpacity: 1,
  cssVariables: { ...DefaultLight.cssVariables, ...openlaneCssVariables },
  themeName: 'openlane',
  colorPalette: 'light',
  isPanelless: true,
}
