'use client'
import React, { useState } from 'react'
import { PageHeading } from '@repo/ui/page-heading'
import MyGroupsTable from '@/components/pages/protected/groups/my-groups/my-groups-table'
import CreateGroupDialog from '../../../../components/pages/protected/groups/my-groups/create-group-dialog'
import { CreditCard as CardIcon, Table as TableIcon } from 'lucide-react'
import { Card } from '@repo/ui/cardpanel'
import MyGroupsCard from '@/components/pages/protected/groups/my-groups/my-groups-cards'
import { Checkbox } from '@repo/ui/checkbox'
import { GetAllGroupsQuery, GroupSettingVisibility } from '@repo/codegen/src/schema'
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@repo/ui/sheet'
import GroupDetailsSheet from '../../../../components/pages/protected/groups/my-groups/my-group-details-sheet'

export interface Group {
  id: string
  name: string
  description?: string
  tags: string[]
  visibility: GroupSettingVisibility
  members: {
    firstName?: string
    avatarFile?: { presignedURL?: string }
    avatarRemoteURL?: string
  }[]
  isManaged: boolean
}

const Page: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'table' | 'card'>('table')
  const [showAutoGenerated, setShowAutoGenerated] = useState<boolean>(true)
  const [selectedGroup, setSelectedGroup] = useState<null | Group>(null)

  console.log('selectedGroup', selectedGroup)
  return (
    <>
      <PageHeading heading="My Groups" />
      <div className="flex justify-between">
        <div className="flex items-center gap-5">
          <div className="flex gap-1 size-fit bg-transparent p-1 border rounded-md">
            <div className={`py-0.5 px-1.5 rounded-md cursor-pointer ${activeTab === 'table' ? 'bg-white' : 'bg-transparent'}`} onClick={() => setActiveTab('table')}>
              <TableIcon />
            </div>
            <div className={`py-0.5 px-1.5 rounded-md cursor-pointer ${activeTab === 'card' ? 'bg-white' : 'bg-transparent'}`} onClick={() => setActiveTab('card')}>
              <CardIcon />
            </div>
          </div>
          <div className="flex gap-1 items-center">
            <Checkbox checked={showAutoGenerated} onCheckedChange={(val: boolean) => setShowAutoGenerated(val)} />
            <p>Show auto generated group</p>
          </div>
        </div>
        <CreateGroupDialog />
      </div>

      {/* Pass the checkbox state as a prop */}
      {activeTab === 'table' ? (
        <MyGroupsTable showAutoGenerated={showAutoGenerated} setSelectedGroup={setSelectedGroup} />
      ) : (
        <MyGroupsCard showAutoGenerated={showAutoGenerated} setSelectedGroup={setSelectedGroup} />
      )}
      <GroupDetailsSheet selectedGroup={selectedGroup} setSelectedGroup={setSelectedGroup} />
    </>
  )
}

export default Page
