version: '3'

tasks:
  codegen:
    desc: run generate + clean
    cmds:
      - task: generate
      - task: clean

  generate:
    desc: run generate
    cmds:
      - bun run codegen --verbose
      - bun run prettier --write src/schema.ts src/historyschema.ts

  clean:
    # See https://github.com/dotansimha/graphql-code-generator-community/issues/501
    # TODO: find the right combination of deps to fix this
    desc: clean up badly generated code
    cmds:
      - |
        for f in src/schema.ts src/historyschema.ts; do
          sed -i.bak "s|'graphql-request/dist/types'|'graphql-request'|g" "$f" && rm -f "$f.bak"
        done
