version: '3'

tasks:
  codegen:
    desc: run generate + clean
    cmds:
      - task: generate
      - task: clean

  generate:
    desc: run generate
    cmd: bun run codegen --verbose

  clean:
    # See https://github.com/dotansimha/graphql-code-generator-community/issues/501
    # TODO: find the right combination of deps to fix this
    desc: clean up badly generated code
    cmd: sed -i.bak "s|'graphql-request/dist/types'|'graphql-request'|g" src/schema.ts && rm -f src/schema.ts.bak
