export enum AccessEnum {
  CanCreateStandard = 'can_create_standard',
  CanCreateEvidence = 'can_create_evidence',
  CanCreateControl = 'can_create_control',
  CanCreateNarrative = 'can_create_narrative',
  CanCreateRisk = 'can_create_risk',
  CanCreateProcedure = 'can_create_procedure',
  CanCreateGroup = 'can_create_group',
  CanCreateControlObjective = 'can_create_control_objective',
  CanDelete = 'can_delete',
  CanCreateTemplate = 'can_create_template',
  CanInviteMembers = 'can_invite_members',
  CanCreateSubcontrol = 'can_create_subcontrol',
  CanCreateInternalPolicy = 'can_create_internal_policy',
  AuditLogViewer = 'audit_log_viewer',
  CanCreateProgram = 'can_create_program',
  CanCreateControlImplementation = 'can_create_control_implementation',
  CanView = 'can_view',
  CanEdit = 'can_edit',
  Member = 'member',
  Owner = 'owner',
  Access = 'access',
  CanInviteAdmins = 'can_invite_admins',
}
