export enum AccessEnum {
  CanCreateTemplate = 'can_create_template',
  CanCreateNarrative = 'can_create_narrative',
  CanInviteAdmins = 'can_invite_admins',
  CanCreateStandard = 'can_create_standard',
  CanCreateJobTemplate = 'can_create_job_template',
  CanInviteMembers = 'can_invite_members',
  CanCreateSubcontrol = 'can_create_subcontrol',
  CanCreateInternalPolicy = 'can_create_internal_policy',
  CanCreateProcedure = 'can_create_procedure',
  CanCreateGroup = 'can_create_group',
  CanManageGroups = 'can_manage_groups',
  CanCreateScheduledJob = 'can_create_scheduled_job',
  AuditLogViewer = 'audit_log_viewer',
  CanCreateRisk = 'can_create_risk',
  CanEdit = 'can_edit',
  CanView = 'can_view',
  CanCreateControlObjective = 'can_create_control_objective',
  CanCreateControlImplementation = 'can_create_control_implementation',
  CanCreateControl = 'can_create_control',
  CanCreateMappedControl = 'can_create_mapped_control',
  CanCreateEvidence = 'can_create_evidence',
  CanCreateProgram = 'can_create_program',
  CanDelete = 'can_delete',
  CanCreateTrustCenterDocument = 'can_create_trust_center_doc',
}
