export enum TableFilterKeysEnum {
  TASK = 'task',
  CONTROL = 'control',
  EVIDENCE = 'evidence',
  POLICY = 'policy',
  PROCEDURE = 'procedure',
  STANDARD_CATALOG = 'standard-catalog',
  QUESTIONNAIRE = 'questionnaire',
  RISK = 'risk',
  SUBSCRIBE = 'subscribe',
  MEMBER = 'member',
  ORG_INVITE = 'org_invite',
  GROUP = 'group',
  PERSONAL_ACCESS_TOKEN = 'personal-access-token',
  API_TOKEN = 'api-token',
  TRUST_CENTER_DOCS = 'trust-center-docs',
  TRUST_CENTER_NDA_REQUESTS = 'trust-center-nda-requests',
  SUBPROCESSORS = 'subprocessors',
  TEMPLATE = 'template',
  CONTROL_DOC_POLICY = 'control-doc-policy',
  CONTROL_DOC_PROCEDURE = 'control-doc-procedure',
  CONTROL_DOC_TASK = 'control-doc-task',
  CONTROL_DOC_RISK = 'control-doc-risk',
}
