import {
  CircleDot,
  FolderPen,
  Key,
  UserRoundCheck,
  UserRoundPen,
  Shapes,
  CalendarClock,
  type LucideIcon,
  CircleDollarSign,
  IdCard,
  ScanEye,
  FileText,
  FileBadge2,
  Folder,
  FolderTree,
  GitBranch,
  Building2,
  CircleGauge,
  Layers,
  Globe2,
  MapPin,
  EarthLock,
  UsersRound,
  MapPlus,
  Link,
  Tag,
  Blend,
  Focus,
  ShieldPlus,
  MessageCircle,
  ShieldCheck,
  KeyRound,
  BookMarked,
} from 'lucide-react'

export enum FilterIconName {
  DisplayID = 'DisplayID',
  Title = 'Title',
  Name = 'Name',
  Type = 'Type',
  Status = 'Status',
  Assigner = 'Assigner',
  Assignee = 'Assignee',
  Date = 'Date',
  Cost = 'Cost',
  ID = 'ID',
  Access = 'Access',
  Category = 'Category',
  Subcategory = 'Subcategory',
  Source = 'Source',
  Team = 'Team',
  Tier = 'Tier',
  Criticality = 'Criticality',
  Environment = 'Environment',
  Scope = 'Scope',
  Location = 'Location',
  Region = 'Region',
  Security = 'Security',
  Tag = 'Tag',
  Relationships = 'Relationships',
  SecurityFeatureSupported = 'SecurityFeatureSupported',
  SecurityFeatureEnforced = 'SecurityFeatureEnforced',
  SSO = 'SSO',
  RefCode = 'RefCode',
  Program = 'Program',
  Standard = 'Standard',
  Owners = 'Owners',
  ProgramName = 'ProgramName',
  LinkedPolicies = 'LinkedPolicies',
  Comments = 'Comments',
  Reference = 'Reference',
}

export const FilterIcons: Record<FilterIconName, LucideIcon> = {
  [FilterIconName.DisplayID]: Key,
  [FilterIconName.Title]: FolderPen,
  [FilterIconName.Name]: FolderPen,
  [FilterIconName.Status]: CircleDot,
  [FilterIconName.Assigner]: UserRoundCheck,
  [FilterIconName.Assignee]: UserRoundPen,
  [FilterIconName.Type]: Shapes,
  [FilterIconName.Date]: CalendarClock,
  [FilterIconName.Cost]: CircleDollarSign,
  [FilterIconName.ID]: IdCard,
  [FilterIconName.Access]: ScanEye,
  [FilterIconName.Category]: Folder,
  [FilterIconName.Subcategory]: FolderTree,
  [FilterIconName.Source]: GitBranch,
  [FilterIconName.Team]: Building2,
  [FilterIconName.Tier]: Layers,
  [FilterIconName.Criticality]: CircleGauge,
  [FilterIconName.Environment]: Globe2,
  [FilterIconName.Location]: MapPin,
  [FilterIconName.Security]: EarthLock,
  [FilterIconName.Region]: MapPlus,
  [FilterIconName.Tag]: Tag,
  [FilterIconName.Relationships]: Blend,
  [FilterIconName.Scope]: Focus,
  [FilterIconName.SecurityFeatureSupported]: ShieldPlus,
  [FilterIconName.SecurityFeatureEnforced]: ShieldCheck,
  [FilterIconName.SSO]: KeyRound,
  [FilterIconName.RefCode]: Key,
  [FilterIconName.Program]: FileText,
  [FilterIconName.Standard]: FileBadge2,
  [FilterIconName.Owners]: UsersRound,
  [FilterIconName.ProgramName]: ShieldCheck,
  [FilterIconName.LinkedPolicies]: Link,
  [FilterIconName.Comments]: MessageCircle,
  [FilterIconName.Reference]: BookMarked,
}
