import { create } from 'zustand'

interface GroupsState {
  activeTab: 'table' | 'card'
  setActiveTab: (tab: 'table' | 'card') => void

  showAutoGenerated: boolean
  setShowAutoGenerated: (value: boolean) => void

  selectedGroup: string | null
  setSelectedGroup: (groupId: string | null) => void

  isAdmin: boolean
  setIsAdmin: (value: boolean) => void
}

export const useMyGroupsStore = create<GroupsState>()((set) => ({
  activeTab: 'table',
  setActiveTab: (tab) => set({ activeTab: tab }),

  showAutoGenerated: true,
  setShowAutoGenerated: (value) => set({ showAutoGenerated: value }),

  selectedGroup: null,
  setSelectedGroup: (groupId) => set({ selectedGroup: groupId }),

  isAdmin: false,
  setIsAdmin: (value) => set({ isAdmin: value }),
}))
