import { Group } from '@/app/(protected)/groups/my-groups/page'
import { create } from 'zustand'

interface GroupsState {
  activeTab: 'table' | 'card'
  setActiveTab: (tab: 'table' | 'card') => void

  showAutoGenerated: boolean
  setShowAutoGenerated: (value: boolean) => void

  selectedGroup: Group | null
  setSelectedGroup: (group: Group | null) => void
}

export const useMyGroupsStore = create<GroupsState>()((set) => ({
  activeTab: 'table',
  setActiveTab: (tab) => set({ activeTab: tab }),

  showAutoGenerated: true,
  setShowAutoGenerated: (value) => set({ showAutoGenerated: value }),

  selectedGroup: null,
  setSelectedGroup: (group) => set({ selectedGroup: group }),
}))
